'use client';

import { useEffect,useState } from 'react';
import { collection,doc,onSnapshot,updateDoc } from 'firebase/firestore';
import { firestore } from '@/lib/firebase-client';
import { AdminShell } from '@/components/admin/AdminShell';
import { useAdminAuth } from '@/components/admin/AdminAuthProvider';

type Row={id:string;[key:string]:any};
const date=(v:any)=>{const d=v?.toDate?.()||new Date(v||0);return Number.isNaN(d.getTime())?'—':d.toLocaleString();};
const money=(v:any)=>`€${(Number(v||0)/100).toFixed(2)}`;
export default function OrdersPage(){
 const {authorised,loading}=useAdminAuth();const [tab,setTab]=useState<'orders'|'customers'|'enquiries'>('orders');const [orders,setOrders]=useState<Row[]>([]);const [customers,setCustomers]=useState<Row[]>([]);const [enquiries,setEnquiries]=useState<Row[]>([]);const [error,setError]=useState('');
 useEffect(()=>{if(loading||!authorised)return;const fail=(e:unknown)=>{console.error(e);setError('Unable to read secure operations data.');};const u=[onSnapshot(collection(firestore,'orders'),s=>setOrders(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>dateValue(b.createdAt)-dateValue(a.createdAt))),fail),onSnapshot(collection(firestore,'customers'),s=>setCustomers(s.docs.map(d=>({id:d.id,...d.data()}))),fail),onSnapshot(collection(firestore,'enquiries'),s=>setEnquiries(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>dateValue(b.createdAt)-dateValue(a.createdAt))),fail)];return()=>u.forEach(x=>x());},[authorised,loading]);
 async function setEnquiryStatus(id:string,status:string){await updateDoc(doc(firestore,'enquiries',id),{status,updatedAt:new Date()});}
 return <AdminShell><div className="admin-page-heading"><p className="admin-kicker">Commerce operations</p><h1>Orders & Customers</h1><p>Review payments, digital delivery, customer history and enquiries.</p></div>{error&&<div className="admin-cms-message">{error}</div>}<div className="admin-toolbar"><button type="button" onClick={()=>setTab('orders')}>Orders ({orders.length})</button><button type="button" onClick={()=>setTab('customers')}>Customers ({customers.length})</button><button type="button" onClick={()=>setTab('enquiries')}>Enquiries ({enquiries.length})</button></div><div className="admin-table-wrap"><table><thead>{tab==='orders'?<tr><th>Date</th><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Payment</th><th>Download</th></tr>:tab==='customers'?<tr><th>Customer</th><th>Email</th><th>Phone</th><th>Stripe ID</th><th>Updated</th></tr>:<tr><th>Date</th><th>Name</th><th>Department</th><th>Subject</th><th>Email</th><th>Status</th></tr>}</thead><tbody>{tab==='orders'?(orders.length?orders.map(o=><tr key={o.id}><td>{date(o.paidAt||o.createdAt)}</td><td>{o.orderNumber||o.id}</td><td>{o.customerName}<br/><small>{o.customerEmail}</small></td><td>{(o.songs||o.items||[]).map((x:any)=>x.title||x.name).join(', ')||'—'}</td><td>{money(o.amountTotal||o.total)}</td><td>{o.paymentStatus||o.status}</td><td>{o.downloadStatus||'—'}</td></tr>):<tr><td colSpan={7}>No orders yet.</td></tr>):tab==='customers'?(customers.length?customers.map(c=><tr key={c.id}><td>{c.name||'—'}</td><td>{c.email||c.id}</td><td>{c.phone||'—'}</td><td>{c.stripeCustomerId||'—'}</td><td>{date(c.updatedAt||c.createdAt)}</td></tr>):<tr><td colSpan={5}>No customers yet.</td></tr>):(enquiries.length?enquiries.map(e=><tr key={e.id}><td>{date(e.createdAt)}</td><td>{e.name}</td><td>{e.department}</td><td><strong>{e.subject}</strong><br/><small>{e.message}</small></td><td><a href={`mailto:${e.email}`}>{e.email}</a></td><td><select value={e.status||'new'} onChange={x=>setEnquiryStatus(e.id,x.target.value)}><option value="new">New</option><option value="read">Read</option><option value="replied">Replied</option><option value="archived">Archived</option><option value="spam">Spam</option></select></td></tr>):<tr><td colSpan={6}>No enquiries yet.</td></tr>)}</tbody></table></div></AdminShell>;
}
function dateValue(v:any){return (v?.toDate?.()||new Date(v||0)).getTime()||0;}