'use client';

import { useEffect, useMemo, useState } from 'react';
import { collection, onSnapshot } from 'firebase/firestore';
import { Download, FileSpreadsheet, Printer } from 'lucide-react';
import { firestore } from '@/lib/firebase-client';
import { AdminShell } from '@/components/admin/AdminShell';
import { useAdminAuth } from '@/components/admin/AdminAuthProvider';

type Period='today'|'yesterday'|'7d'|'30d'|'month'|'lastMonth'|'quarter'|'year'|'custom';
type Row=Record<string,any>;
type Range={start:Date;end:Date;label:string};
const asDate=(v:any)=>v?.toDate?.()||new Date(v||0);
const money=(c:number)=>`€${(Number(c||0)/100).toFixed(2)}`;
const dayStart=(d:Date)=>{const x=new Date(d);x.setHours(0,0,0,0);return x};
const dayEnd=(d:Date)=>{const x=new Date(d);x.setHours(23,59,59,999);return x};
const esc=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;
function rangeFor(period:Period,customStart:string,customEnd:string):Range{const now=new Date();let start=dayStart(now),end=dayEnd(now),label='Today';if(period==='yesterday'){const d=new Date(now);d.setDate(d.getDate()-1);start=dayStart(d);end=dayEnd(d);label='Yesterday';}if(period==='7d'){start=dayStart(new Date(now.getFullYear(),now.getMonth(),now.getDate()-6));label='Last 7 days';}if(period==='30d'){start=dayStart(new Date(now.getFullYear(),now.getMonth(),now.getDate()-29));label='Last 30 days';}if(period==='month'){start=new Date(now.getFullYear(),now.getMonth(),1);label='This month';}if(period==='lastMonth'){start=new Date(now.getFullYear(),now.getMonth()-1,1);end=dayEnd(new Date(now.getFullYear(),now.getMonth(),0));label='Last month';}if(period==='quarter'){start=new Date(now.getFullYear(),Math.floor(now.getMonth()/3)*3,1);label='This quarter';}if(period==='year'){start=new Date(now.getFullYear(),0,1);label='This year';}if(period==='custom'){start=customStart?dayStart(new Date(`${customStart}T00:00:00`)):dayStart(now);end=customEnd?dayEnd(new Date(`${customEnd}T00:00:00`)):dayEnd(now);label=`${start.toLocaleDateString()} – ${end.toLocaleDateString()}`;}return{start,end,label};}
function groupAdd(map:Map<string,{name:string;sales:number;revenue:number}>,name:string,sales:number,revenue:number){const key=name||'Unknown';const cur=map.get(key)||{name:key,sales:0,revenue:0};cur.sales+=sales;cur.revenue+=revenue;map.set(key,cur);}

export default function AnalyticsPage(){
 const {authorised,loading}=useAdminAuth();
 const [period,setPeriod]=useState<Period>('month');const [customStart,setCustomStart]=useState('');const [customEnd,setCustomEnd]=useState('');
 const [orders,setOrders]=useState<Row[]>([]);const [downloads,setDownloads]=useState<Row[]>([]);const [customers,setCustomers]=useState<Row[]>([]);const [events,setEvents]=useState<Row[]>([]);const [error,setError]=useState('');
 useEffect(()=>{if(loading||!authorised)return;const fail=(e:unknown)=>{console.error(e);setError('Unable to read analytics. Confirm administrator permissions.');};const u=[onSnapshot(collection(firestore,'orders'),s=>setOrders(s.docs.map(d=>({id:d.id,...d.data()}))),fail),onSnapshot(collection(firestore,'downloads'),s=>setDownloads(s.docs.map(d=>({id:d.id,...d.data()}))),fail),onSnapshot(collection(firestore,'customers'),s=>setCustomers(s.docs.map(d=>({id:d.id,...d.data()}))),fail),onSnapshot(collection(firestore,'analyticsEvents'),s=>setEvents(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setEvents([]))];return()=>u.forEach(x=>x());},[authorised,loading]);
 const range=useMemo(()=>rangeFor(period,customStart,customEnd),[period,customStart,customEnd]);
 const inRange=(v:any)=>{const t=asDate(v).getTime();return t>=range.start.getTime()&&t<=range.end.getTime()};
 const paid=useMemo(()=>orders.filter(o=>String(o.status||o.paymentStatus)==='paid'&&inRange(o.paidAt||o.createdAt)),[orders,range]);
 const report=useMemo(()=>{let revenue=0,fees=0,songSales=0,productSales=0;const songs=new Map(),artists=new Map(),albums=new Map(),products=new Map(),countries=new Map(),devices=new Map(),sources=new Map();for(const o of paid){const total=Number(o.amountTotal||o.total||0),fee=Number(o.stripeFee||o.feeAmount||0);revenue+=total;fees+=fee;groupAdd(countries,String(o.country||o.customerCountry||o.shippingAddress?.country||'Unknown'),1,total);groupAdd(devices,String(o.deviceType||'Unknown'),1,total);groupAdd(sources,String(o.trafficSource||o.utmSource||'Direct / unknown'),1,total);for(const s of Array.isArray(o.songs)?o.songs:[]){const q=Number(s.quantity||1),unit=Number(s.unitAmount||0)||(o.songs?.length?Math.round(total/o.songs.length):0),r=q*unit;songSales+=q;groupAdd(songs,String(s.title||s.name||s.id||'Song'),q,r);groupAdd(artists,String(s.artist||s.artistName||'Unknown artist'),q,r);groupAdd(albums,String(s.albumTitle||'Singles / no album'),q,r);}for(const p of Array.isArray(o.items)?o.items.filter((x:any)=>!x.digital):[]){const q=Number(p.quantity||1),unit=Number(p.unitAmount||p.price||0),r=q*unit;productSales+=q;groupAdd(products,String(p.name||p.title||p.id||'Product'),q,r);}}
 const views=events.filter(e=>inRange(e.createdAt)&&['page_view','session'].includes(String(e.type))).length;const checkouts=events.filter(e=>inRange(e.createdAt)&&String(e.type)==='checkout_started').length;const conversion=views?paid.length/views*100:0;const newCustomers=customers.filter(c=>inRange(c.createdAt)).length;const usedDownloads=downloads.filter(d=>inRange(d.usedAt)&&Number(d.downloadCount||0)>0).length;const sorted=(m:Map<any,any>)=>[...m.values()].sort((a,b)=>b.revenue-a.revenue||b.sales-a.sales);
 return{revenue,fees,net:revenue-fees,orders:paid.length,songSales,productSales,newCustomers,downloads:usedDownloads,average:paid.length?Math.round(revenue/paid.length):0,views,checkouts,conversion,songs:sorted(songs),artists:sorted(artists),albums:sorted(albums),products:sorted(products),countries:sorted(countries),devices:sorted(devices),sources:sorted(sources)};},[paid,downloads,customers,events,range]);
 const generatedAt=new Date();
 function rows(){return [['AUREON MUSIC GROUP ANALYTICS'],['Generated',generatedAt.toLocaleString()],['Reporting period',range.label],['From',range.start.toLocaleString()],['To',range.end.toLocaleString()],[],['SUMMARY'],['Revenue EUR',report.revenue/100],['Stripe fees EUR',report.fees/100],['Net revenue EUR',report.net/100],['Orders',report.orders],['New customers',report.newCustomers],['Downloads',report.downloads],['Average order EUR',report.average/100],['Conversion rate %',Number(report.conversion.toFixed(2))],[],['TOP SONGS'],['Song','Sales','Revenue EUR'],...report.songs.map((x:any)=>[x.name,x.sales,x.revenue/100]),[],['TOP ARTISTS'],['Artist','Sales','Revenue EUR'],...report.artists.map((x:any)=>[x.name,x.sales,x.revenue/100]),[],['TOP ALBUMS'],['Album','Sales','Revenue EUR'],...report.albums.map((x:any)=>[x.name,x.sales,x.revenue/100]),[],['TOP MERCHANDISE'],['Product','Sales','Revenue EUR'],...report.products.map((x:any)=>[x.name,x.sales,x.revenue/100]),[],['GEOGRAPHIC SALES'],['Country','Orders','Revenue EUR'],...report.countries.map((x:any)=>[x.name,x.sales,x.revenue/100]),[],['DEVICES'],['Device','Orders','Revenue EUR'],...report.devices.map((x:any)=>[x.name,x.sales,x.revenue/100]),[],['TRAFFIC SOURCES'],['Source','Orders','Revenue EUR'],...report.sources.map((x:any)=>[x.name,x.sales,x.revenue/100])];}
 async function exportExcel(){const ExcelJS=(await import('exceljs')).default;const wb=new ExcelJS.Workbook();wb.creator='Aureon Music Group';wb.created=generatedAt;const ws=wb.addWorksheet('Analytics',{views:[{state:'frozen',ySplit:7}]});ws.columns=[{width:34},{width:18},{width:20}];try{const r=await fetch('/images/branding/Aureon_Header_Logo.png');if(r.ok){const b=await r.arrayBuffer();const id=wb.addImage({buffer:b,extension:'png'});ws.addImage(id,{tl:{col:0,row:0},ext:{width:250,height:72}});}}catch{}ws.mergeCells('A1:C4');ws.getCell('A5').value='AUREON MUSIC GROUP — BUSINESS ANALYTICS';ws.mergeCells('A5:C5');ws.getCell('A5').font={bold:true,size:18,color:{argb:'FFB79A4A'}};ws.getCell('A6').value=`Downloaded: ${generatedAt.toLocaleString()}  |  Period: ${range.label}`;ws.mergeCells('A6:C6');ws.getCell('A6').font={italic:true,color:{argb:'FF666666'}};for(const row of rows().slice(6)){const r=ws.addRow(row);if(row.length===1){r.font={bold:true,color:{argb:'FFFFFFFF'}};r.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF111111'}};}else if(String(row[0]).includes('Revenue')||String(row[0]).includes('Average')){r.getCell(2).numFmt='€#,##0.00';}}ws.eachRow(row=>{row.alignment={vertical:'middle'};row.eachCell(cell=>{cell.border={bottom:{style:'hair',color:{argb:'FFD8C58A'}}};});});const buf=await wb.xlsx.writeBuffer();const url=URL.createObjectURL(new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download=`Aureon-Analytics-${generatedAt.toISOString().replace(/[:.]/g,'-')}.xlsx`;a.click();URL.revokeObjectURL(url);}
 function exportCsv(){const csv=rows().map(r=>r.map(esc).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`Aureon-Analytics-${generatedAt.toISOString().replace(/[:.]/g,'-')}.csv`;a.click();URL.revokeObjectURL(url);}
 const table=(title:string,data:any[],label:string)=><article><h2>{title}</h2><div className="admin-table-wrap"><table><thead><tr><th>{label}</th><th>Sales / Orders</th><th>Revenue</th></tr></thead><tbody>{data.length?data.slice(0,20).map((x:any)=><tr key={x.name}><td>{x.name}</td><td>{x.sales}</td><td>{money(x.revenue)}</td></tr>):<tr><td colSpan={3}>No data for this period.</td></tr>}</tbody></table></div></article>;
 return <AdminShell><div className="admin-page-heading"><p className="admin-kicker">Business intelligence</p><h1>Analytics</h1><p>Track sales, customers, catalogue performance, geography, devices and traffic sources.</p></div>{error&&<div className="admin-cms-message">{error}</div>}<div className="admin-toolbar"><label>Period <select value={period} onChange={e=>setPeriod(e.target.value as Period)}><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="month">This month</option><option value="lastMonth">Last month</option><option value="quarter">Quarter</option><option value="year">Year</option><option value="custom">Custom range</option></select></label>{period==='custom'&&<><label>From <input type="date" value={customStart} onChange={e=>setCustomStart(e.target.value)}/></label><label>To <input type="date" value={customEnd} onChange={e=>setCustomEnd(e.target.value)}/></label></>}<button className="primary-button" onClick={exportExcel}><FileSpreadsheet size={16}/> Excel</button><button onClick={exportCsv}><Download size={16}/> CSV</button><button onClick={()=>window.print()}><Printer size={16}/> Print</button></div><section className="admin-stat-grid">{[['Revenue',money(report.revenue)],['Stripe fees',money(report.fees)],['Net revenue',money(report.net)],['Orders',report.orders],['Customers',report.newCustomers],['Downloads',report.downloads],['Average order',money(report.average)],['Conversion',`${report.conversion.toFixed(2)}%`]].map(([l,v])=><article key={String(l)}><span>{l}</span><strong>{v}</strong></article>)}</section><section className="admin-dashboard-grid">{table('Best-selling songs',report.songs,'Song')}{table('Best-selling artists',report.artists,'Artist')}{table('Revenue by album',report.albums,'Album')}{table('Top merchandise',report.products,'Product')}{table('Geographic sales',report.countries,'Country')}{table('Device types',report.devices,'Device')}{table('Traffic sources',report.sources,'Source')}</section></AdminShell>;
}
