import { FieldValue } from 'firebase-admin/firestore';
import { adminFirestore } from '@/lib/firebase-admin';
import type { SearchDocument,SearchHit,SearchProvider,SearchRequest,SearchResponse } from './types';
const norm=(v:unknown)=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const words=(v:string)=>norm(v).split(/\s+/).filter(Boolean);
function distance(a:string,b:string){const m=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=1;j<=b.length;j++)m[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)m[i][j]=Math.min(m[i-1][j]+1,m[i][j-1]+1,m[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return m[a.length][b.length]}
function fuzzy(term:string,target:string){if(!term)return 0;if(target===term)return 1;if(target.startsWith(term))return .92;if(target.includes(term))return .82;const d=distance(term,target);return d<=1?.72:d===2&&term.length>5?.55:0}
function score(doc:SearchDocument,q:string){const terms=words(q);if(!terms.length)return {score:doc.popularity/100,matched:[] as string[]};const title=norm(doc.title),subtitle=norm(doc.subtitle),description=norm(doc.description),tokens=doc.tokens.map(norm);let total=0;const matched:string[]=[];for(const term of terms){let best=fuzzy(term,title)*10;best=Math.max(best,fuzzy(term,subtitle)*6);for(const token of tokens)best=Math.max(best,fuzzy(term,token)*4);if(description.includes(term))best=Math.max(best,2);if(best>0)matched.push(term);total+=best;}if(matched.length<terms.length)return {score:0,matched};total+=Math.log10(1+Math.max(0,doc.popularity))*1.4;const age=doc.releaseDate?Math.max(0,(Date.now()-new Date(doc.releaseDate).getTime())/86400000):9999;if(age<30)total+=1.5;else if(age<180)total+=.8;return {score:total,matched}}
export class FirestoreSearchProvider implements SearchProvider{
 async search(input:SearchRequest):Promise<SearchResponse>{const snap=await adminFirestore.collection('searchIndex').limit(3000).get();let docs=snap.docs.map(d=>d.data() as SearchDocument);const f=input.filters||{};if(f.types?.length)docs=docs.filter(d=>f.types!.includes(d.type));if(f.genre)docs=docs.filter(d=>norm(d.genre)===norm(f.genre));if(f.artistId)docs=docs.filter(d=>d.artistId===f.artistId);if(f.year)docs=docs.filter(d=>d.year===f.year);if(f.mood)docs=docs.filter(d=>norm(d.mood)===norm(f.mood));const ranked=docs.map(doc=>{const s=score(doc,input.query);return {...doc,score:s.score,matchedTerms:s.matched} as SearchHit}).filter(h=>input.query? h.score>0:true).sort((a,b)=>b.score-a.score);const facet={types:{} as Record<string,number>,genres:{} as Record<string,number>,artists:{} as Record<string,number>,years:{} as Record<string,number>};for(const d of ranked){facet.types[d.type]=(facet.types[d.type]||0)+1;if(d.genre)facet.genres[d.genre]=(facet.genres[d.genre]||0)+1;if(d.artistName)facet.artists[d.artistName]=(facet.artists[d.artistName]||0)+1;if(d.year)facet.years[String(d.year)]=(facet.years[String(d.year)]||0)+1}const suggestions=[...new Set(ranked.slice(0,8).flatMap(h=>[h.title,h.subtitle]).filter(Boolean))].slice(0,8);return{query:input.query,hits:ranked.slice(0,Math.min(100,input.limit||30)),total:ranked.length,facets:facet,suggestions,provider:'firestore-v1'}}
 async upsert(documents:SearchDocument[]){const batch=adminFirestore.batch();documents.forEach(d=>batch.set(adminFirestore.collection('searchIndex').doc(`${d.type}_${d.id}`),{...d,indexedAt:FieldValue.serverTimestamp()}));await batch.commit()}
 async remove(ids:string[]){const batch=adminFirestore.batch();ids.forEach(id=>batch.delete(adminFirestore.collection('searchIndex').doc(id)));await batch.commit()}
 async clear(){const snap=await adminFirestore.collection('searchIndex').get();for(let i=0;i<snap.docs.length;i+=400){const batch=adminFirestore.batch();snap.docs.slice(i,i+400).forEach(d=>batch.delete(d.ref));await batch.commit()}}
}
export const searchProvider:SearchProvider=new FirestoreSearchProvider();
