import { adminFirestore } from '@/lib/firebase-admin';
import { searchProvider } from './engine';
import type { SearchContentType,SearchDocument } from './types';
const MAP:Record<SearchContentType,string>={artist:'artists',album:'albums',song:'songs',video:'videos',news:'newsArticles',playlist:'publicPlaylists'};
const slug=(v:unknown)=>String(v||'').trim();const text=(v:unknown)=>String(v||'').trim();const num=(v:unknown)=>Number(v||0)||0;
function document(type:SearchContentType,id:string,data:Record<string,any>):SearchDocument|null{if(type!=='playlist'&&String(data.status||'').toLowerCase()!=='published')return null;if(type==='playlist'&&data.public!==true&&data.isPublic!==true)return null;const d=data.details||{};const title=text(data.title||data.name||d.title||d.name);if(!title)return null;const artistName=text(data.artistName||data.artist||d.artistName);const artistSlug=text(data.artistSlug||d.artistSlug);const ownSlug=slug(data.slug||id);const base=type==='artist'?'/artists/':type==='album'?'/music/':type==='song'?'/songs/':type==='video'?'/videos/':type==='news'?'/news/':'/community/playlists/';const genre=text(data.genre||d.genre);const mood=text(data.mood||d.mood);const releaseDate=text(data.releaseDate||d.releaseDate||data.publishedAt);const year=Number(text(data.year||d.year||(releaseDate?new Date(releaseDate).getFullYear():'')))||undefined;const description=text(data.description||data.bio||data.excerpt||d.description);const tags=[genre,mood,artistName,...(Array.isArray(data.tags)?data.tags:[]),...(Array.isArray(d.tags)?d.tags:[])].filter(Boolean).map(String);return{id,type,title,subtitle:type==='artist'?genre:artistName||text(data.type||d.type),description,url:`${base}${ownSlug}`,image:text(data.coverImageUrl||data.imageUrl||data.profileImageUrl||data.thumbnailUrl||data.featuredImageUrl||d.coverImageUrl||d.imageUrl||'/images/branding/Aureon_Header_Logo.png'),artistId:text(data.artistId||d.artistId)||undefined,artistName:artistName||undefined,genre:genre||undefined,mood:mood||undefined,year,releaseDate:releaseDate||undefined,popularity:num(data.monthlyPlays||data.plays30d||data.views||data.popularity||d.popularity),tokens:[title,artistName,genre,mood,description,...tags].flatMap(v=>String(v).toLowerCase().split(/[^a-z0-9]+/)).filter(Boolean),status:'published',updatedAt:new Date().toISOString()}}
export async function indexCollection(type:SearchContentType){const snap=await adminFirestore.collection(MAP[type]).get();const docs=snap.docs.map(s=>document(type,s.id,s.data())).filter(Boolean) as SearchDocument[];const existing=await adminFirestore.collection('searchIndex').where('type','==',type).get();const keep=new Set(docs.map(d=>`${type}_${d.id}`));await searchProvider.upsert(docs);await searchProvider.remove(existing.docs.filter(d=>!keep.has(d.id)).map(d=>d.id));return docs.length}
export async function indexOne(type:SearchContentType,id:string){const snap=await adminFirestore.collection(MAP[type]).doc(id).get();const key=`${type}_${id}`;if(!snap.exists){await searchProvider.remove([key]);return false}const doc=document(type,id,snap.data()||{});if(!doc){await searchProvider.remove([key]);return false}await searchProvider.upsert([doc]);return true}
export async function rebuildSearchIndex(){await searchProvider.clear();const result:Record<string,number>={};for(const type of Object.keys(MAP) as SearchContentType[])result[type]=await indexCollection(type);await adminFirestore.collection('searchIndexMeta').doc('status').set({provider:'firestore-v1',counts:result,lastRebuiltAt:new Date().toISOString()},{merge:true});return result}
export const collectionToSearchType=(collection:string):SearchContentType|null=>({artists:'artist',albums:'album',songs:'song',videos:'video',newsArticles:'news',publicPlaylists:'playlist'} as Record<string,SearchContentType>)[collection]||null;
