import type {Metadata} from 'next';
import {headers} from 'next/headers';
import MusicPlayerProvider from '@/components/music/MusicPlayerProvider';
import BackgroundPlaybackBridge from '@/components/music/BackgroundPlaybackBridge';
import ListenerExperienceMount from '@/components/member/ListenerExperienceMount';
import RoutePrefetcher from '@/components/RoutePrefetcher';
import WebVitalsReporter from '@/components/WebVitalsReporter';
import GrowthAnalyticsBridge from '@/components/GrowthAnalyticsBridge';
import {TrustAnalyticsBridge} from '@/components/trust/TrustAnalyticsBridge';
import {I18nProvider} from '@/components/i18n/I18nProvider';
import {GlobalInterfaceTranslator} from '@/components/i18n/GlobalInterfaceTranslator';
import {defaultLocale,isLocale,localeMeta,localePath,locales,stripLocale} from '@/lib/i18n/config';
import {getDictionary} from '@/lib/i18n/dictionaries';
import {DEFAULT_IMAGE,SITE_NAME,SITE_URL,safeJsonLd} from '@/lib/seo';
import './globals.css';import './finish.css';import './sprint2.css';import './artists-header-fix.css';import './homepage-fit-fix.css';import './artist-profiles.css';import './music-catalogue.css';import './video-catalogue.css';import './news.css';import './merch-store.css';import './about.css';import './about-cleanup.css';import './contact.css';import './digital-music-store.css';import './footer.css';import './phase1-polish.css';import './admin.css';import './admin-phase2-final.css';import './admin-dashboard-polish.css';import './trust-phase-a.css';import './product-trust-phase-b.css';import './home-media-override.css';
const AUREON_ICON='/images/branding/Aureon_Header_Logo.png';
async function requestLocale(){const value=(await headers()).get('x-aureon-locale')||defaultLocale;return isLocale(value)?value:defaultLocale;}
export async function generateMetadata():Promise<Metadata>{const requestHeaders=await headers();const localeValue=requestHeaders.get('x-aureon-locale')||defaultLocale;const locale=isLocale(localeValue)?localeValue:defaultLocale;const dictionary=getDictionary(locale);const rawPath=requestHeaders.get('x-aureon-path')||'/';const basePath=stripLocale(rawPath);const canonical=`${SITE_URL}${localePath(basePath,locale)}`;const languages=Object.fromEntries(locales.map(item=>[localeMeta[item].html,`${SITE_URL}${localePath(basePath,item)}`]));return {metadataBase:new URL(SITE_URL),title:{default:dictionary.seo.title,template:`%s | ${SITE_NAME}`},description:dictionary.seo.description,applicationName:SITE_NAME,icons:{icon:[{url:AUREON_ICON,type:'image/png'}],shortcut:[AUREON_ICON],apple:[{url:AUREON_ICON,type:'image/png'}]},alternates:{canonical,languages:{...languages,'x-default':`${SITE_URL}${basePath}`}},robots:{index:true,follow:true,googleBot:{index:true,follow:true,'max-image-preview':'large','max-snippet':-1,'max-video-preview':-1}},openGraph:{title:dictionary.seo.title,description:dictionary.seo.description,url:canonical,siteName:SITE_NAME,images:[{url:DEFAULT_IMAGE,width:1200,height:630,alt:SITE_NAME}],locale:localeMeta[locale].html.replace('-','_'),alternateLocale:locales.filter(item=>item!==locale).map(item=>localeMeta[item].html.replace('-','_')),type:'website'},twitter:{card:'summary_large_image',title:dictionary.seo.title,description:dictionary.seo.description,images:[DEFAULT_IMAGE]}};}
export default async function RootLayout({children}:{children:React.ReactNode}){const locale=await requestLocale();const dictionary=getDictionary(locale);const description=dictionary.seo.description;const organizationSchema={'@type':'Organization','@id':`${SITE_URL}/#organization`,name:SITE_NAME,url:SITE_URL,logo:`${SITE_URL}${DEFAULT_IMAGE}`,description};const websiteSchema={'@type':'WebSite','@id':`${SITE_URL}/#website`,name:SITE_NAME,url:SITE_URL,inLanguage:localeMeta[locale].html,publisher:{'@id':`${SITE_URL}/#organization`},potentialAction:{'@type':'SearchAction',target:`${SITE_URL}${localePath('/search',locale)}?q={search_term_string}`,'query-input':'required name=search_term_string'}};const rootSchema={'@context':'https://schema.org','@graph':[organizationSchema,websiteSchema]};return <html lang={localeMeta[locale].html}><body><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(rootSchema)}}/><I18nProvider locale={locale}><GlobalInterfaceTranslator/><MusicPlayerProvider>{children}<BackgroundPlaybackBridge/><ListenerExperienceMount/><RoutePrefetcher/><WebVitalsReporter/><GrowthAnalyticsBridge/><TrustAnalyticsBridge/></MusicPlayerProvider></I18nProvider></body></html>;}
