'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {onAuthStateChanged} from 'firebase/auth';
import {Briefcase,Menu,Search,UserRound,X} from 'lucide-react';
import {Logo} from './Logo';import {TrustBar} from './TrustBar';import {LanguageSwitcher} from '@/components/i18n/LanguageSwitcher';import {useI18n} from '@/components/i18n/I18nProvider';
import {useSiteFeatures} from '@/lib/useSiteFeatures';import {usePublishedDocument} from '@/lib/usePublishedDocument';import {firebaseAuth} from '@/lib/firebase-client';import {localePath,stripLocale} from '@/lib/i18n/config';
type NavigationLink=[string,string];
const defaults={homeLabel:'Home',artistsLabel:'Artists',musicLabel:'Music',videosLabel:'Videos',merchLabel:'Merch',membershipLabel:'Membership',newsLabel:'News',aboutLabel:'About',contactLabel:'Contact',accountLabel:'Member account',homeHref:'/',artistsHref:'/artists',musicHref:'/music',videosHref:'/videos',merchHref:'/merchandise',membershipHref:'/membership',newsHref:'/news',aboutHref:'/about',contactHref:'/contact',accountHref:'/account'};
function isActive(pathname:string,href:string){const path=stripLocale(pathname);if(href==='/')return path==='/';return path===href||path.startsWith(`${href}/`)}
export function Header(){const pathname=usePathname();const{locale,dictionary}=useI18n();const{features}=useSiteFeatures();const{data}=usePublishedDocument<any>('sitePages','header',defaults);const value={...defaults,...(data||{})};const[signedIn,setSignedIn]=useState(Boolean(firebaseAuth.currentUser));const[mobileOpen,setMobileOpen]=useState(false);useEffect(()=>onAuthStateChanged(firebaseAuth,user=>setSignedIn(Boolean(user))),[]);useEffect(()=>setMobileOpen(false),[pathname]);const n=dictionary.nav;const labels=locale==='en'?{home:value.homeLabel,artists:value.artistsLabel,music:value.musicLabel,videos:value.videosLabel,membership:value.membershipLabel,news:value.newsLabel,about:value.aboutLabel,contact:value.contactLabel}:{home:n.home,artists:n.artists,music:n.music,videos:n.videos,membership:n.membership,news:n.news,about:n.about,contact:n.contact};const local=(href:string)=>localePath(href,locale);const links:NavigationLink[]=[[labels.home,value.homeHref],[labels.artists,value.artistsHref],[labels.music,value.musicHref],[labels.videos,value.videosHref],...(features.merchandiseEnabled?[[value.merchLabel,value.merchHref] as NavigationLink]:[]),[labels.membership,value.membershipHref],[labels.news,value.newsHref],[labels.about,value.aboutHref],[labels.contact,value.contactHref]];return <><header className="site-header premium-label-header"><Logo/><nav className="desktop-nav" aria-label="Main navigation">{links.map(([label,href])=><Link key={href} href={local(href)} className={isActive(pathname,href)?'active':''}>{label}</Link>)}</nav><div className="header-actions"><LanguageSwitcher/><Link href={local('/search')} className="header-icon" aria-label={n.search}><Search size={20}/></Link>{features.merchandiseEnabled&&<Link href={local(value.merchHref)} className="header-icon" aria-label="Store"><Briefcase size={20}/></Link>}<Link href={local(value.accountHref)} className="member-login-link" aria-label={signedIn?n.account:n.login}><UserRound size={18}/><span>{signedIn?n.account:n.login}</span></Link><button type="button" className="mobile-menu-toggle" aria-label={mobileOpen?'Close navigation':'Open navigation'} aria-expanded={mobileOpen} aria-controls="mobile-main-navigation" onClick={()=>setMobileOpen(open=>!open)}>{mobileOpen?<X size={22}/>:<Menu size={22}/>}</button></div></header><nav id="mobile-main-navigation" className={`mobile-nav-panel${mobileOpen?' open':''}`} aria-label="Mobile navigation" aria-hidden={!mobileOpen}>{links.map(([label,href])=><Link key={href} href={local(href)} className={isActive(pathname,href)?'active':''} onClick={()=>setMobileOpen(false)}>{label}</Link>)}<Link href={local(value.accountHref)} className={isActive(pathname,value.accountHref)?'active':''} onClick={()=>setMobileOpen(false)}>{signedIn?n.account:n.login}</Link></nav><TrustBar/></>}
