'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, Play, Newspaper } from 'lucide-react';
import { ArtworkImage } from './ArtworkImage';
import { Footer } from './Footer';
import { HomeArtistRotation } from './HomeArtistRotation';
import { PreviewGatedVideo } from './video/PreviewGatedVideo';
import { getArtwork } from '@/lib/get-artwork';
import { usePublishedCollection, type PublicRecord } from '@/lib/use-published-collection';
import { useSiteFeatures } from '@/lib/useSiteFeatures';
import styles from './HomeFeaturedContent.module.css';

type News=PublicRecord&{title?:string;slug?:string;excerpt?:string;description?:string;featuredImageUrl?:string;imageUrl?:string;publishAt?:any;publishDate?:string;featured?:boolean;details?:Record<string,any>};
type Video=PublicRecord&{title?:string;slug?:string;artistName?:string;thumbnailUrl?:string;videoUrl?:string;externalUrl?:string;youtubeUrl?:string;vimeoUrl?:string;featured?:boolean;shortForm?:boolean;type?:string;details?:Record<string,any>};

export function HomeFeaturedContent(){
 const{features}=useSiteFeatures();const{items:news}=usePublishedCollection<News>('newsArticles',[]);const{items:videos}=usePublishedCollection<Video>('videos',[]);const[videoIndex,setVideoIndex]=useState(0);const[paused,setPaused]=useState(false);
 const featuredNews=news.filter(x=>x.featured).slice(0,3);const latestNews=(featuredNews.length?featuredNews:news).slice(0,3);const featuredVideos=videos.filter(x=>x.featured).slice(0,5);const latestVideos=(featuredVideos.length?featuredVideos:videos).slice(0,5);const activeVideo=latestVideos[videoIndex]||null;
 useEffect(()=>{if(paused||latestVideos.length<2)return;const timer=window.setInterval(()=>setVideoIndex(current=>(current+1)%latestVideos.length),8000);return()=>window.clearInterval(timer)},[paused,latestVideos.length]);
 useEffect(()=>{if(videoIndex>=latestVideos.length)setVideoIndex(0)},[videoIndex,latestVideos.length]);
 const move=(direction:1|-1)=>setVideoIndex(current=>((current+direction)%latestVideos.length+latestVideos.length)%latestVideos.length);
 return <><HomeArtistRotation/><section className={`content-panel ${styles.deferredSection}`}><div className="section-heading"><div><p className="eyebrow">Latest stories</p><h2>News from Aureon</h2></div><Link href="/news" className="ghost-button">View all news →</Link></div>{latestNews.length?<div className={styles.grid}>{latestNews.map(item=><article className={`news-card ${styles.card}`} key={item.id}><div className={styles.newsImage}><ArtworkImage src={getArtwork(item)} alt={item.title||'Aureon news'} fill loading="lazy" sizes="(max-width:760px) 100vw, (max-width:1200px) 50vw, 33vw"/></div><p className="eyebrow"><Newspaper size={14}/> {item.featured?'Featured news':'Latest news'}</p><h3>{item.title}</h3><p>{item.excerpt||item.description}</p><Link href={`/news/${item.slug||item.id}`}>Read story →</Link></article>)}</div>:<div className="store-empty"><p>Published news will appear here automatically.</p></div>}</section>
 {features.videosEnabled&&<section className={`${styles.videoSection} ${styles.deferredSection}`}><div className={styles.videoHeading}><div><p className="eyebrow">Watch now</p><h2>Featured videos</h2></div><Link href="/videos" className="ghost-button">View all videos →</Link></div>{activeVideo?<article className={styles.videoHero} onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocusCapture={()=>setPaused(true)} onBlurCapture={()=>setPaused(false)}>{latestVideos.length>1&&<button className={`${styles.videoArrow} ${styles.videoPrev}`} type="button" onClick={()=>move(-1)} aria-label="Previous featured video"><ChevronLeft/></button>}<div className={styles.videoMedia}>{(()=>{const details=activeVideo.details||{};const direct=String(activeVideo.videoUrl||details.videoUrl||'').trim();const poster=getArtwork(activeVideo);return direct?<PreviewGatedVideo src={direct} poster={poster} title={activeVideo.title||'Aureon video'} className={styles.inlineVideo}/>:<Link href={`/videos/${activeVideo.slug||activeVideo.id}`} className={styles.videoPosterLink} aria-label={`Play ${activeVideo.title||'Aureon video'} on Aureon`}><ArtworkImage src={poster} alt={activeVideo.title||'Aureon video'} fill sizes="(max-width:760px) 100vw, 1400px"/><span><Play size={30}/></span></Link>})()}</div><div className={styles.videoOverlay}><p>{activeVideo.shortForm?'Short-form clip':activeVideo.type||activeVideo.details?.type||'Featured video'}</p><h3>{activeVideo.title}</h3><span>{activeVideo.artistName||activeVideo.details?.artistName}</span><Link href={`/videos/${activeVideo.slug||activeVideo.id}`}>View video page →</Link></div>{latestVideos.length>1&&<button className={`${styles.videoArrow} ${styles.videoNext}`} type="button" onClick={()=>move(1)} aria-label="Next featured video"><ChevronRight/></button>}</article>:<div className="store-empty"><p>Featured videos will appear here when published in the Control Center.</p></div>}</section>}<Footer/></>
}
