'use client';

import type { AnalyticsContext, AttributionTouch, ContentAttribution } from './analytics-model';

export const ANALYTICS_CONSENT_KEY = 'aureon-analytics-consent';
export const ANALYTICS_CONSENT_COOKIE = 'aureon_analytics_consent';
export type AnalyticsConsentChoice = 'granted'|'denied';
const FIRST_TOUCH_KEY='aureon-analytics-first-touch', SESSION_TOUCH_KEY='aureon-analytics-session-touch', CONTENT_KEY='aureon-analytics-content';
const VISITOR_KEY='aureon-analytics-visitor', SESSION_KEY='aureon-analytics-session', LAST_VISIT_KEY='aureon-analytics-last-visit';
const emptyTouch=():AttributionTouch=>({source:'direct',medium:'none',campaign:'',content:'',term:'',referrer:'',landingPage:'/'});
const safe=(value:unknown,max=180)=>String(value||'').trim().slice(0,max);
const campaignValue=(value:unknown)=>safe(value,100).toLowerCase().replace(/\s+/g,'_').replace(/[^a-z0-9._-]/g,'');
const parse=<T>(storage:Storage,key:string,fallback:T):T=>{try{return JSON.parse(storage.getItem(key)||'') as T}catch{return fallback}};

function validConsent(value:string|null|undefined):value is AnalyticsConsentChoice{return value==='granted'||value==='denied'}
function consentCookie(){if(typeof document==='undefined')return null;const entry=String(document.cookie||'').split(';').map(value=>value.trim()).find(value=>value.startsWith(`${ANALYTICS_CONSENT_COOKIE}=`));const value=entry?decodeURIComponent(entry.slice(entry.indexOf('=')+1)):null;return validConsent(value)?value:null}
function writeConsentCookie(choice:AnalyticsConsentChoice){if(typeof document==='undefined')return;const host=location.hostname.toLowerCase(),sharedDomain=host==='aureonmusicgroup.com'||host.endsWith('.aureonmusicgroup.com')?'; Domain=.aureonmusicgroup.com':'';document.cookie=`${ANALYTICS_CONSENT_COOKIE}=${choice}; Max-Age=31536000; Path=/; SameSite=Lax${location.protocol==='https:'?'; Secure':''}${sharedDomain}`}
export function getAnalyticsConsentChoice():AnalyticsConsentChoice|null{if(typeof window==='undefined')return null;const stored=localStorage.getItem(ANALYTICS_CONSENT_KEY);if(validConsent(stored)){writeConsentCookie(stored);return stored}const cookie=consentCookie();if(cookie)localStorage.setItem(ANALYTICS_CONSENT_KEY,cookie);return cookie}
export function analyticsConsent(){return getAnalyticsConsentChoice()==='granted'}
function externalReferrer(){if(!document.referrer)return'';try{const url=new URL(document.referrer);return url.hostname===location.hostname?'':safe(url.origin,300)}catch{return''}}
function inferredSource(referrer:string){if(!referrer)return{source:'direct',medium:'none'};const host=new URL(referrer).hostname.replace(/^www\./,'').toLowerCase();if(host.includes('google.'))return{source:'google',medium:'organic_search'};if(host.includes('tiktok.'))return{source:'tiktok',medium:'organic_social'};if(host.includes('instagram.'))return{source:'instagram',medium:'organic_social'};if(host.includes('youtube.')||host==='youtu.be')return{source:'youtube',medium:'organic_social'};return{source:campaignValue(host)||'referral',medium:'referral'}}
function landingTouch():AttributionTouch{const params=new URLSearchParams(location.search),referrer=externalReferrer(),inferred=inferredSource(referrer),campaign=new URLSearchParams();for(const key of ['utm_source','utm_medium','utm_campaign','utm_content','utm_term']){const value=campaignValue(params.get(key));if(value)campaign.set(key,value)}return{source:campaignValue(params.get('utm_source'))||inferred.source,medium:campaignValue(params.get('utm_medium'))||inferred.medium,campaign:campaignValue(params.get('utm_campaign')),content:campaignValue(params.get('utm_content')),term:campaignValue(params.get('utm_term')),referrer,landingPage:safe(location.pathname+(campaign.size?`?${campaign}`:''),300)}}
function id(storage:Storage,key:string){let value=storage.getItem(key)||'';if(!value){value=crypto.randomUUID();storage.setItem(key,value)}return value}
export function initialiseAttribution(){if(!analyticsConsent())return{returning:false};const touch=landingTouch();if(!localStorage.getItem(FIRST_TOUCH_KEY))localStorage.setItem(FIRST_TOUCH_KEY,JSON.stringify(touch));if(!sessionStorage.getItem(SESSION_TOUCH_KEY))sessionStorage.setItem(SESSION_TOUCH_KEY,JSON.stringify(touch));const returning=Boolean(localStorage.getItem(LAST_VISIT_KEY));localStorage.setItem(LAST_VISIT_KEY,new Date().toISOString());id(localStorage,VISITOR_KEY);id(sessionStorage,SESSION_KEY);return{returning}}
export function recordContentView(kind:'song'|'artist',slug:string){if(!analyticsConsent()||!slug)return;const current=parse<ContentAttribution>(localStorage,CONTENT_KEY,{});if(kind==='song'){current.firstSongViewed||=slug;current.lastSongViewed=slug}else{current.firstArtistViewed||=slug;current.lastArtistViewed=slug}localStorage.setItem(CONTENT_KEY,JSON.stringify(current))}
export function getAnalyticsContext():AnalyticsContext|null{if(!analyticsConsent())return null;initialiseAttribution();return{consent:true,visitorId:id(localStorage,VISITOR_KEY),sessionId:id(sessionStorage,SESSION_KEY),firstTouch:parse(localStorage,FIRST_TOUCH_KEY,emptyTouch()),sessionTouch:parse(sessionStorage,SESSION_TOUCH_KEY,emptyTouch()),content:parse(localStorage,CONTENT_KEY,{})}}
export function analyticsCheckoutContext(){const context=getAnalyticsContext();return context?{analyticsConsent:true,analyticsClientId:context.visitorId,analyticsSessionId:context.sessionId,firstTouch:context.firstTouch,sessionTouch:context.sessionTouch,contentAttribution:context.content}:{analyticsConsent:false}}
export function setAnalyticsConsent(granted:boolean){const choice:AnalyticsConsentChoice=granted?'granted':'denied';localStorage.setItem(ANALYTICS_CONSENT_KEY,choice);writeConsentCookie(choice);if(!granted){for(const key of [FIRST_TOUCH_KEY,CONTENT_KEY,VISITOR_KEY,LAST_VISIT_KEY])localStorage.removeItem(key);for(const key of [SESSION_TOUCH_KEY,SESSION_KEY])sessionStorage.removeItem(key);window.gtag?.('consent','update',{analytics_storage:'denied'})}window.dispatchEvent(new CustomEvent('aureon-consent-change',{detail:{granted}}))}
