'use client';

type Row = Record<string, any>;
type Input = { report:any; orders:Row[]; members:Row[]; events:Row[]; customers:Row[]; downloads:Row[]; start:Date; end:Date };
declare global { interface Window { ExcelJS?: any } }

const NAVY='10233F',GOLD='C9A24D',WHITE='FFFFFF',PALE='EAF0F6';
const asDate=(v:any)=>v?.toDate?.()||new Date(v||0);
const cents=(v:any)=>Number(v||0)/100;
const inRange=(v:any,start:Date,end:Date)=>{const d=asDate(v);return d>=start&&d<=end};
const country=(v:any)=>String(v||'Unknown');
const anon=(v:any)=>String(v||'').slice(0,36);
async function excel(){if(window.ExcelJS)return window.ExcelJS;await new Promise<void>((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js';s.onload=()=>resolve();s.onerror=()=>reject(new Error('Excel reporting library could not be loaded.'));document.head.appendChild(s)});return window.ExcelJS}
function setup(ws:any,widths:number[]){ws.views=[{state:'frozen',ySplit:4,showGridLines:false}];widths.forEach((w,i)=>ws.getColumn(i+1).width=w);ws.pageSetup={orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0};ws.headerFooter={oddFooter:'&LAureon Music Group&CConfidential analytics export&RPage &P of &N'};}
function title(ws:any,text:string,subtitle:string,cols:number){ws.mergeCells(1,1,1,cols);ws.getCell(1,1).value=text;ws.getCell(1,1).font={size:20,bold:true,color:{argb:WHITE}};ws.getCell(1,1).fill={type:'pattern',pattern:'solid',fgColor:{argb:NAVY}};ws.mergeCells(2,1,2,cols);ws.getCell(2,1).value=subtitle;ws.getCell(2,1).font={size:10,color:{argb:WHITE}};ws.getCell(2,1).fill={type:'pattern',pattern:'solid',fgColor:{argb:NAVY}};ws.getRow(1).height=32;ws.getRow(2).height=22}
function table(ws:any,name:string,columns:string[],rows:any[][]){ws.addTable({name:name.replace(/[^A-Za-z0-9]/g,''),ref:'A4',headerRow:true,style:{theme:'TableStyleMedium2',showRowStripes:true},columns:columns.map(name=>({name})),rows});ws.getRow(4).eachCell((c:any)=>{c.font={bold:true,color:{argb:WHITE}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:GOLD}};c.alignment={wrapText:true}})}
function sheet(wb:any,name:string,heading:string,subtitle:string,columns:string[],rows:any[][],widths:number[]){const ws=wb.addWorksheet(name);setup(ws,widths);title(ws,heading,subtitle,columns.length);table(ws,name,columns,rows);return ws}

export async function exportLiveAnalyticsWorkbook(input:Input){
 const ExcelJS=await excel(),wb=new ExcelJS.Workbook(),now=new Date();
 wb.creator='Aureon Music Group';wb.company='Aureon Music Group';wb.title='Aureon Live Analytics';wb.created=now;wb.calcProperties.fullCalcOnLoad=true;
 const events=input.events.filter(e=>inRange(e.createdAt||e.receivedAt,input.start,input.end));
 const orders=input.orders.filter(o=>inRange(o.paidAt||o.createdAt,input.start,input.end));
 const members=input.members.filter(m=>inRange(m.createdAt||m.updatedAt||input.start,input.start,input.end));
 const customers=input.customers.filter(c=>inRange(c.createdAt||c.updatedAt,input.start,input.end));
 const downloads=input.downloads.filter(d=>inRange(d.usedAt||d.createdAt,input.start,input.end));
 const generated=`${input.start.toLocaleDateString('en-IE')} – ${input.end.toLocaleDateString('en-IE')} | Snapshot generated ${now.toLocaleString('en-IE')}`;
 const totalPlays=input.report.songs.reduce((s:number,x:any)=>s+Number(x.plays||0),0);
 const totalCompletes=input.report.songs.reduce((s:number,x:any)=>s+Number(x.completes||0),0);
 const uniqueVisitors=new Set(events.map(e=>e.visitorId).filter(Boolean)).size,uniqueSessions=new Set(events.map(e=>e.sessionId).filter(Boolean)).size;
 const dash=wb.addWorksheet('Executive Dashboard');setup(dash,[24,22,24,22,24,22]);title(dash,'AUREON MUSIC GROUP — LIVE ANALYTICS',generated,6);
 const kpis=[['Gross revenue',cents(input.report.gross)],['Net revenue',cents(input.report.net)],['Paid orders',input.report.orders],['Active subscriptions',input.report.active],['Tracked events',events.length],['Anonymous visitors',uniqueVisitors],['Sessions',uniqueSessions],['Song plays',totalPlays],['Song completions',totalCompletes],['New customers',input.report.newCustomers],['Downloads',input.report.downloads],['Data refreshed',now.toLocaleString('en-IE')]];
 dash.getRow(4).values=['Metric','Value','Metric','Value','Metric','Value'];dash.getRow(4).eachCell((c:any)=>{c.font={bold:true,color:{argb:WHITE}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:GOLD}}});for(let i=0;i<kpis.length;i+=3){const r=5+i/3;dash.getRow(r).values=[kpis[i]?.[0],kpis[i]?.[1],kpis[i+1]?.[0],kpis[i+1]?.[1],kpis[i+2]?.[0],kpis[i+2]?.[1]];dash.getRow(r).fill={type:'pattern',pattern:'solid',fgColor:{argb:PALE}}}
 sheet(wb,'Songs','SONG PERFORMANCE',generated,['Song','Artist','Album','Plays','Completed','Preview Completed','Completion %','Avg Listen sec','Sales','Revenue EUR','Top Country'],input.report.songs.map((x:any)=>[x.name,x.artistName||'',x.albumTitle||'',x.plays,x.completes,x.previewCompletes,x.completionRate,x.avgListen,x.sales,cents(x.revenue),x.topCountries?.[0]?.[0]||'Unknown']),[30,24,26,12,12,18,14,16,12,16,20]);
 sheet(wb,'Artists','ARTIST PERFORMANCE',generated,['Artist','Plays','Completed','Sales','Revenue EUR','Top Country'],input.report.artists.map((x:any)=>[x.name,x.plays,x.completes,x.sales,cents(x.revenue),x.topCountries?.[0]?.[0]||'Unknown']),[30,14,14,14,18,22]);
 sheet(wb,'Albums','ALBUM PERFORMANCE',generated,['Album','Plays','Completed','Sales','Revenue EUR','Top Country'],input.report.albums.map((x:any)=>[x.name,x.plays,x.completes,x.sales,cents(x.revenue),x.topCountries?.[0]?.[0]||'Unknown']),[32,14,14,14,18,22]);
 sheet(wb,'Geography','GEOGRAPHIC PERFORMANCE',generated,['Country','Activity','Sales','Revenue EUR'],input.report.countries.map((x:any)=>[x.name,(x.plays||0)+(x.views||0)+(x.completes||0)+(x.cartAdds||0),x.sales,cents(x.revenue)]),[28,16,14,18]);
 sheet(wb,'Regions','REGIONAL PERFORMANCE',generated,['Region','Activity','Sales','Revenue EUR'],input.report.regions.map((x:any)=>[x.name,(x.plays||0)+(x.views||0)+(x.completes||0)+(x.cartAdds||0),x.sales,cents(x.revenue)]),[38,16,14,18]);
 sheet(wb,'Cities','CITY PERFORMANCE',generated,['City','Activity','Sales','Revenue EUR'],input.report.cities.map((x:any)=>[x.name,(x.plays||0)+(x.views||0)+(x.completes||0)+(x.cartAdds||0),x.sales,cents(x.revenue)]),[38,16,14,18]);
 sheet(wb,'Devices','DEVICE PERFORMANCE',generated,['Device','Activity','Sales','Revenue EUR'],input.report.devices.map((x:any)=>[x.name,(x.plays||0)+(x.views||0)+(x.completes||0)+(x.cartAdds||0),x.sales,cents(x.revenue)]),[28,16,14,18]);
 sheet(wb,'Traffic Sources','TRAFFIC & ATTRIBUTION',generated,['Source / Referrer','Activity','Sales','Revenue EUR'],input.report.referrers.map((x:any)=>[x.name,(x.plays||0)+(x.views||0)+(x.completes||0)+(x.cartAdds||0),x.sales,cents(x.revenue)]),[44,16,14,18]);
 sheet(wb,'Event Data','EVENT DATA — PIVOT READY',`${generated} | Anonymous IDs only; no email, phone, postal address or payment credentials exported.`,['Date','Event','Entity Type','Title','Artist','Album','Path','Country','Region','City','Device','Locale','Timezone','First Source','First Medium','First Campaign','First Content','First Term','Session Source','Session Medium','Session Campaign','Initial Referrer','Landing Page','Listened sec','Progress %','Session','Anonymous Visitor'],events.map(e=>[asDate(e.createdAt||e.receivedAt),e.eventType||e.type,e.entityType,e.title||e.entityId,e.artistName||e.artistId,e.albumTitle,e.pathname,country(e.country),e.region,e.city,e.deviceType,e.locale,e.timezone,e.firstTouchSource,e.firstTouchMedium,e.firstTouchCampaign,e.firstTouchContent,e.firstTouchTerm,e.sessionSource,e.sessionMedium,e.sessionCampaign,e.initialReferrer,e.firstLandingPage,Number(e.listenedSeconds||0),Number(e.progressPercent||0),anon(e.sessionId),anon(e.visitorId)]),[20,24,16,30,24,24,34,18,20,20,14,14,22,18,18,24,20,18,18,18,24,34,34,14,12,22,22]);
 sheet(wb,'Orders','ORDER & CONVERSION DATA',generated,['Date','Status','Amount EUR','Currency','Country','Traffic Source','UTM Source','UTM Medium','UTM Campaign','Session Source','Session Medium','Session Campaign','Landing Page','Initial Referrer','First Song','Last Song','First Artist','Last Artist','Anonymous Session'],orders.map(o=>[asDate(o.paidAt||o.createdAt),o.status||o.paymentStatus,cents(o.amountTotal||o.total),o.currency||'EUR',country(o.country||o.customerCountry||o.shippingAddress?.country),o.trafficSource,o.utmSource,o.utmMedium,o.utmCampaign,o.sessionSource,o.sessionMedium,o.sessionCampaign,o.initialLandingPage||o.firstLandingPage,o.initialReferrer,o.firstSongViewed,o.lastSongViewed,o.firstArtistViewed,o.lastArtistViewed,anon(o.analyticsSessionId||o.sessionId)]),[20,16,16,12,18,20,18,18,24,18,18,24,34,34,24,24,24,24,22]);
 sheet(wb,'Membership','MEMBERSHIP PERFORMANCE',generated,['Created / Updated','Status','Plan','Country','Referral Code'],members.map(m=>[asDate(m.createdAt||m.updatedAt),m.subscriptionStatus||m.status,m.plan||m.membershipPlan,country(m.country),m.referralCode||'']),[22,18,20,18,20]);
 sheet(wb,'Customers','CUSTOMER GROWTH',`${generated} | Direct personal identifiers intentionally excluded.`,['Created','Country','Plan / Type'],customers.map(c=>[asDate(c.createdAt),country(c.country),c.plan||c.type||'']),[22,20,24]);
 sheet(wb,'Downloads','DOWNLOAD ACTIVITY',generated,['Date','Download Count','Product / Song','Country'],downloads.map(d=>[asDate(d.usedAt||d.createdAt),Number(d.downloadCount||0),d.title||d.productName||d.songTitle||d.productId||'',country(d.country)]),[22,18,34,20]);
 const buffer=await wb.xlsx.writeBuffer();const blob=new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Aureon-Live-Analytics-${now.toISOString().replace(/[:.]/g,'-')}.xlsx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);
}
