'use client';

type AnyRow={id?:string;[key:string]:any};
type ExecutiveExportInput={report:any;orders:AnyRow[];members:AnyRow[];events:AnyRow[];refunds?:AnyRow[];expenses?:AnyRow[];start:Date;end:Date};

declare global{interface Window{ExcelJS?:any}}

const NAVY='10233F',GOLD='C9A24D',WHITE='FFFFFF',PALE='EAF0F6',INK='1F2937',GREEN='18864B',RED='C62828',GREY='667085';
const euro='€#,##0.00;[Red](€#,##0.00);-';
const integer='#,##0;[Red](#,##0);-';
const pct='0.0%;[Red](0.0%);-';
const safe=(v:any)=>String(v??'').replace(/[\\/*?:\[\]]/g,' ').slice(0,31)||'Sheet';
const asDate=(v:any)=>v?.toDate?.()||new Date(v||0);
const cents=(v:any)=>Number(v||0)/100;
const countryNames:Record<string,string>={IE:'Ireland',GB:'United Kingdom',US:'United States',PT:'Portugal',ES:'Spain',FR:'France',DE:'Germany',IT:'Italy',NL:'Netherlands',BE:'Belgium',BR:'Brazil',ZA:'South Africa',CA:'Canada',AU:'Australia',NZ:'New Zealand',MX:'Mexico',AE:'United Arab Emirates',CH:'Switzerland',AT:'Austria',SE:'Sweden',NO:'Norway',DK:'Denmark',FI:'Finland',PL:'Poland',GR:'Greece',JP:'Japan',IN:'India'};
const countryLabel=(value:any)=>{const code=String(value||'').trim().toUpperCase();if(!code||code==='UNKNOWN'||code==='NOT CAPTURED')return 'Not captured — legacy order';return countryNames[code]||code};

async function excel(){if(window.ExcelJS)return window.ExcelJS;await new Promise<void>((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js';s.onload=()=>resolve();s.onerror=()=>reject(new Error('Excel reporting library could not be loaded.'));document.head.appendChild(s)});return window.ExcelJS}

function title(ws:any,text:string,subtitle:string,cols=10){ws.mergeCells(1,1,1,cols);const c=ws.getCell(1,1);c.value=text;c.font={name:'Aptos Display',size:22,bold:true,color:{argb:WHITE}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:NAVY}};c.alignment={vertical:'middle'};ws.getRow(1).height=34;ws.mergeCells(2,1,2,cols);const s=ws.getCell(2,1);s.value=subtitle;s.font={name:'Aptos',size:10,color:{argb:'D7E2F0'}};s.fill={type:'pattern',pattern:'solid',fgColor:{argb:NAVY}};ws.getRow(2).height=22}
function section(ws:any,row:number,text:string,cols=10){ws.mergeCells(row,1,row,cols);const c=ws.getCell(row,1);c.value=text;c.font={bold:true,color:{argb:WHITE},size:11};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:NAVY}};c.alignment={vertical:'middle'};ws.getRow(row).height=22}
function header(row:any){row.eachCell((c:any)=>{c.font={bold:true,color:{argb:WHITE}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:GOLD}};c.alignment={vertical:'middle',horizontal:'center',wrapText:true};c.border={bottom:{style:'thin',color:{argb:NAVY}}}});row.height=28}
function base(ws:any){ws.views=[{state:'frozen',ySplit:3,showGridLines:false}];ws.properties.defaultRowHeight=18;ws.pageSetup={orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0,paperSize:9,margins:{left:0.25,right:0.25,top:0.5,bottom:0.5,header:0.2,footer:0.2}};ws.headerFooter={oddFooter:'&LAureon Music Group&CConfidential Executive Report&RPage &P of &N'};}
function widths(ws:any,widths:number[]){widths.forEach((w,i)=>ws.getColumn(i+1).width=w)}
function addTable(ws:any,name:string,ref:string,columns:string[],rows:any[][]){ws.addTable({name:name.replace(/[^A-Za-z0-9_]/g,'').slice(0,250),ref,headerRow:true,totalsRow:false,style:{theme:'TableStyleMedium2',showRowStripes:true},columns:columns.map(name=>({name})),rows});header(ws.getRow(Number(ref.match(/\d+/)?.[0]||1)));}
function conditional(ws:any,range:string){ws.addConditionalFormatting({ref:range,rules:[{type:'colorScale',cfvo:[{type:'min'},{type:'percentile',value:50},{type:'max'}],color:[{argb:'FEE2E2'},{argb:'FEF3C7'},{argb:'DCFCE7'}]}]})}
function kpi(ws:any,row:number,col:number,label:string,value:any,format?:string){ws.mergeCells(row,col,row,col+1);ws.mergeCells(row+1,col,row+2,col+1);const l=ws.getCell(row,col),v=ws.getCell(row+1,col);l.value=label.toUpperCase();l.font={size:9,bold:true,color:{argb:GREY}};l.alignment={horizontal:'center'};v.value=value;v.font={size:18,bold:true,color:{argb:NAVY}};v.fill={type:'pattern',pattern:'solid',fgColor:{argb:PALE}};v.alignment={horizontal:'center',vertical:'middle'};if(format)v.numFmt=format;for(let r=row;r<=row+2;r++)for(let c=col;c<=col+1;c++)ws.getCell(r,c).border={top:{style:'thin',color:{argb:'D0D5DD'}},bottom:{style:'thin',color:{argb:'D0D5DD'}},left:{style:'thin',color:{argb:'D0D5DD'}},right:{style:'thin',color:{argb:'D0D5DD'}}}}
function monthly(input:ExecutiveExportInput){const map=new Map<string,{revenue:number,fees:number,refunds:number,expenses:number,orders:number}>();const ensure=(d:Date)=>{const k=d.toISOString().slice(0,7);if(!map.has(k))map.set(k,{revenue:0,fees:0,refunds:0,expenses:0,orders:0});return map.get(k)!};for(const o of input.orders){if(String(o.status||o.paymentStatus).toLowerCase()!=='paid')continue;const d=asDate(o.paidAt||o.createdAt);if(d<input.start||d>input.end)continue;const x=ensure(d);x.revenue+=cents(o.amountTotal);x.fees+=cents(o.stripeFee||o.feeAmount);x.orders++}for(const r of input.refunds||[]){const d=asDate(r.createdAt||r.updatedAt);if(d<input.start||d>input.end)continue;ensure(d).refunds+=cents(r.amount||r.amountRefunded)}for(const e of input.expenses||[]){const d=asDate(e.date||e.createdAt);if(d<input.start||d>input.end)continue;ensure(d).expenses+=cents(e.amount)}return [...map.entries()].sort().map(([month,v])=>({month,...v,net:v.revenue-v.fees-v.refunds-v.expenses}))}
function geographyIdentity(input:ExecutiveExportInput){const map=new Map<string,{visitors:Set<string>,sessions:Set<string>}>();for(const e of input.events){const d=asDate(e.createdAt||e.receivedAt);if(d<input.start||d>input.end)continue;const country=countryLabel(e.country);const item=map.get(country)||{visitors:new Set<string>(),sessions:new Set<string>()};if(e.visitorId)item.visitors.add(String(e.visitorId));if(e.sessionId)item.sessions.add(String(e.sessionId));map.set(country,item)}return map}

export async function exportExecutiveWorkbook(input:ExecutiveExportInput){const ExcelJS=await excel();const wb=new ExcelJS.Workbook();wb.creator='Aureon Music Group';wb.company='Aureon Music Group';wb.subject='Executive Intelligence and Board Reporting';wb.title='Aureon Music Group Executive Dashboard';wb.created=new Date();wb.calcProperties.fullCalcOnLoad=true;
 const r=input.report;const months=monthly(input);const geoIdentity=geographyIdentity(input);const totalPlays=r.songs.reduce((s:number,x:any)=>s+Number(x.plays||0),0);const totalCompletes=r.songs.reduce((s:number,x:any)=>s+Number(x.completes||0),0);const merchViews=r.products.reduce((s:number,x:any)=>s+Number(x.views||0),0);const cartAdds=r.products.reduce((s:number,x:any)=>s+Number(x.cartAdds||0),0);
 const dash=wb.addWorksheet('Executive Dashboard',{properties:{tabColor:{argb:GOLD}}});base(dash);widths(dash,[18,18,18,18,18,18,18,18,18,18,18,18]);title(dash,'AUREON MUSIC GROUP — EXECUTIVE INTELLIGENCE',`Board report | ${input.start.toLocaleDateString('en-IE')} – ${input.end.toLocaleDateString('en-IE')} | Generated ${new Date().toLocaleString('en-IE')}`,12);
 kpi(dash,4,1,'Gross revenue',cents(r.gross),euro);kpi(dash,4,3,'Net revenue',cents(r.net),euro);kpi(dash,4,5,'Paid orders',r.orders,integer);kpi(dash,4,7,'Active members',r.active,integer);kpi(dash,4,9,'Song plays',totalPlays,integer);kpi(dash,4,11,'Completion rate',totalPlays?totalCompletes/totalPlays:0,pct);
 kpi(dash,8,1,'Tracked events',r.eventCount,integer);kpi(dash,8,3,'Merch views',merchViews,integer);kpi(dash,8,5,'Cart additions',cartAdds,integer);kpi(dash,8,7,'Merch cart rate',merchViews?cartAdds/merchViews:0,pct);kpi(dash,8,9,'Top artist',r.artists[0]?.name||'—');kpi(dash,8,11,'Top country',r.countries[0]?.name||'—');
 section(dash,12,'PERFORMANCE TREND',12);dash.getRow(13).values=['Month','Gross Revenue','Net Contribution','Orders','','Top Artists','','Top Songs','','Top Countries'];header(dash.getRow(13));months.forEach((m:any,i:number)=>{const row=14+i;dash.getRow(row).values=[m.month,m.revenue,m.net,m.orders];dash.getCell(row,2).numFmt=euro;dash.getCell(row,3).numFmt=euro});r.artists.slice(0,10).forEach((x:any,i:number)=>{dash.getCell(14+i,6).value=x.name;dash.getCell(14+i,7).value=cents(x.revenue);dash.getCell(14+i,7).numFmt=euro});r.songs.slice(0,10).forEach((x:any,i:number)=>{dash.getCell(14+i,8).value=x.name;dash.getCell(14+i,9).value=x.plays});r.countries.slice(0,10).forEach((x:any,i:number)=>{dash.getCell(14+i,10).value=x.name;dash.getCell(14+i,11).value=x.plays+x.views+x.cartAdds+x.completes});conditional(dash,`B14:C${Math.max(14,13+months.length)}`);conditional(dash,'G14:G23');conditional(dash,'I14:I23');conditional(dash,'K14:K23');dash.autoFilter={from:'A13',to:'D13'};
 section(dash,26,'EXECUTIVE DECISION SIGNALS',12);const signals=[r.artists[0]?`Highest-performing artist: ${r.artists[0].name} (${r.artists[0].plays||0} plays; €${cents(r.artists[0].revenue).toFixed(2)} revenue).`:'Artist data will populate as activity is recorded.',r.countries[0]?`Leading market: ${r.countries[0].name}. Prioritise localisation, creator partnerships and paid media testing in this market.`:'Country data will populate as activity is recorded.',totalPlays&&!totalCompletes?'Listening starts are being captured but no completions were recorded. Review event implementation and preview length.':`Overall completion rate is ${totalPlays?Math.round(totalCompletes/totalPlays*100):0}%.`,merchViews&&cartAdds/merchViews<0.05?'Merchandise cart conversion is below 5%. Review pricing, imagery, shipping clarity and product-page persuasion.':'Merchandise conversion is within the current measured range.'];signals.forEach((x,i)=>{dash.mergeCells(27+i,1,27+i,12);dash.getCell(27+i,1).value='• '+x;dash.getCell(27+i,1).alignment={wrapText:true};dash.getCell(27+i,1).font={color:{argb:INK}};dash.getRow(27+i).height=28});
 
 const songs=wb.addWorksheet('Songs — Master Data');base(songs);widths(songs,[28,22,22,12,12,14,14,14,14,14,18]);title(songs,'SONG PERFORMANCE — MASTER DATA','Native Excel table: use column filters to analyse artist, album, country and performance.',11);addTable(songs,'SongsMaster','A4',['Song','Artist','Album','Plays','Completed','Preview Completed','Completion %','Avg Listen (sec)','Sales','Revenue (€)','Top Country'],r.songs.map((x:any)=>[x.name,x.artistName||'',x.albumTitle||'',x.plays,x.completes,x.previewCompletes,(x.completionRate||0)/100,x.avgListen,x.sales,cents(x.revenue),x.topCountries?.[0]?.[0]||'Unknown']));songs.getColumn(7).numFmt=pct;songs.getColumn(10).numFmt=euro;conditional(songs,`D5:J${Math.max(5,4+r.songs.length)}`);
 const albums=wb.addWorksheet('Albums');base(albums);widths(albums,[30,18,18,18,18,18,20]);title(albums,'ALBUM PERFORMANCE','Album-level listening, sales, revenue and geographic performance.',7);addTable(albums,'AlbumsMaster','A4',['Album','Plays','Completed','Completion %','Sales','Revenue (€)','Top Country'],r.albums.map((x:any)=>[x.name,x.plays,x.completes,(x.completionRate||0)/100,x.sales,cents(x.revenue),x.topCountries?.[0]?.[0]||'Unknown']));albums.getColumn(4).numFmt=pct;albums.getColumn(6).numFmt=euro;conditional(albums,`B5:F${Math.max(5,4+r.albums.length)}`);
 for(const a of r.artists){const ws=wb.addWorksheet(safe(`Artist - ${a.name}`));base(ws);widths(ws,[28,18,18,18,18,18,22,22]);title(ws,`${String(a.name).toUpperCase()} — ARTIST REPORT`,`Performance for ${input.start.toLocaleDateString('en-IE')} – ${input.end.toLocaleDateString('en-IE')}`,8);kpi(ws,4,1,'Plays',a.plays,integer);kpi(ws,4,3,'Completed',a.completes,integer);kpi(ws,4,5,'Sales',a.sales,integer);kpi(ws,4,7,'Revenue',cents(a.revenue),euro);section(ws,8,'ARTIST SONGS',8);const artistSongs=r.songs.filter((s:any)=>String(s.artistName||s.artist||'').toLowerCase()===String(a.name).toLowerCase()||input.events.some(e=>(e.title||e.entityId)===s.name&&(e.artistName||e.artistId)===a.name));addTable(ws,`Artist${safe(a.name)}Songs`,'A9',['Song','Album','Plays','Completed','Completion %','Avg Listen','Sales','Revenue (€)'],artistSongs.map((s:any)=>[s.name,s.albumTitle||'',s.plays,s.completes,(s.completionRate||0)/100,s.avgListen,s.sales,cents(s.revenue)]));ws.getColumn(5).numFmt=pct;ws.getColumn(8).numFmt=euro;section(ws,Math.max(12,10+artistSongs.length),'TOP COUNTRIES',8);(a.topCountries||[]).slice(0,20).forEach((x:any,i:number)=>{ws.getCell(Math.max(13,11+artistSongs.length)+i,1).value=x[0];ws.getCell(Math.max(13,11+artistSongs.length)+i,2).value=x[1]})}
 const merch=wb.addWorksheet('Merchandise');base(merch);widths(merch,[30,14,14,16,14,16,22]);title(merch,'MERCHANDISE PERFORMANCE','Product demand, cart conversion, sales, revenue and market concentration.',7);addTable(merch,'MerchandiseMaster','A4',['Product','Views','Cart Adds','Cart Rate %','Units Sold','Revenue (€)','Top Country'],r.products.map((x:any)=>[x.name,x.views,x.cartAdds,(x.cartRate||0)/100,x.sales,cents(x.revenue),x.topCountries?.[0]?.[0]||'Unknown']));merch.getColumn(4).numFmt=pct;merch.getColumn(6).numFmt=euro;conditional(merch,`B5:F${Math.max(5,4+r.products.length)}`);
 const geo=wb.addWorksheet('Geography');base(geo);widths(geo,[26,16,16,16,18,16,16,18]);title(geo,'GEOGRAPHIC MARKET INTELLIGENCE','Country performance separated into people, sessions, listening behaviour and commercial results.',8);addTable(geo,'CountryPerformance','A4',['Country','Unique Visitors','Sessions','Song Plays','Completed Plays','Cart Adds','Purchases','Revenue (€)'],r.countries.map((x:any)=>{const identity=geoIdentity.get(x.name)||{visitors:new Set<string>(),sessions:new Set<string>()};return[x.name,identity.visitors.size,identity.sessions.size,x.plays,x.completes,x.cartAdds,x.sales,cents(x.revenue)]}));geo.getColumn(8).numFmt=euro;conditional(geo,`B5:H${Math.max(5,4+r.countries.length)}`);let gr=7+r.countries.length;section(geo,gr,'REGIONAL PERFORMANCE',8);geo.getRow(gr+1).values=['Region','Interactions','Plays','Completed','Cart Adds','Sales','Revenue (€)'];header(geo.getRow(gr+1));r.regions.forEach((x:any,i:number)=>geo.getRow(gr+2+i).values=[x.name,x.plays+x.views+x.completes+x.cartAdds,x.plays,x.completes,x.cartAdds,x.sales,cents(x.revenue)]);
 const fin=wb.addWorksheet('Financial Summary');base(fin);widths(fin,[34,16,16,16,16,16,16]);title(fin,'FINANCIAL SUMMARY','Management accounts based on currently recorded transactions. Update assumptions and expenses for complete statutory reporting.',7);section(fin,4,'INCOME STATEMENT',7);fin.getRow(5).values=['Metric',...months.map((m:any)=>m.month),'Total'];header(fin.getRow(5));const lines=[['Gross revenue','revenue'],['Stripe/payment fees','fees'],['Refunds','refunds'],['Operating expenses','expenses'],['Net contribution','net']];lines.forEach((line:any,i:number)=>{const rr=6+i;fin.getCell(rr,1).value=line[0];months.forEach((m:any,j:number)=>{fin.getCell(rr,2+j).value=m[line[1]];fin.getCell(rr,2+j).numFmt=euro});const startCol=2,endCol=1+months.length;fin.getCell(rr,endCol+1).value={formula:`SUM(${fin.getCell(rr,startCol).address}:${fin.getCell(rr,endCol).address})`};fin.getCell(rr,endCol+1).numFmt=euro;if(i===4)fin.getRow(rr).font={bold:true}});section(fin,13,'KEY FINANCIAL RATIOS',7);fin.getRow(14).values=['Net margin',r.gross?r.net/r.gross:0,'Revenue per order',r.orders?cents(r.gross)/r.orders:0,'Revenue per active member',r.active?cents(r.gross)/r.active:0];fin.getCell(14,2).numFmt=pct;fin.getCell(14,4).numFmt=euro;fin.getCell(14,6).numFmt=euro;
 const bs=wb.addWorksheet('Balance Sheet');base(bs);widths(bs,[38,20,20]);title(bs,'MANAGEMENT BALANCE SHEET','Input cash, inventory, receivables and liabilities in the blue cells. Calculations update automatically.',3);section(bs,4,'ASSETS',3);const bsRows=[['Cash and bank',0],['Stripe balance',0],['Accounts receivable',0],['Merchandise inventory',0],['Equipment and other assets',0],['Total assets',{formula:'SUM(B5:B9)'}],['',null],['LIABILITIES',null],['Accounts payable',0],['Tax payable',0],['Deferred subscription revenue',0],['Other liabilities',0],['Total liabilities',{formula:'SUM(B13:B16)'}],['',null],['EQUITY',null],['Share capital',0],['Retained earnings',{formula:"'Financial Summary'!B10"}],['Total equity',{formula:'SUM(B20:B21)'}],['Balance check',{formula:'B10-B17-B22'}]];bsRows.forEach((x:any,i:number)=>{const rr=5+i;bs.getCell(rr,1).value=x[0];bs.getCell(rr,2).value=x[1];bs.getCell(rr,2).numFmt=euro;if(typeof x[1]==='number'){bs.getCell(rr,2).font={color:{argb:'0000FF'}};bs.getCell(rr,2).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF2CC'}}}});['B10','B17','B22','B23'].forEach(a=>bs.getCell(a).font={bold:true,color:{argb:NAVY}});bs.addConditionalFormatting({ref:'B23',rules:[{type:'cellIs',operator:'notEqual',formulae:[0],style:{font:{color:{argb:WHITE},bold:true},fill:{type:'pattern',pattern:'solid',fgColor:{argb:RED}}}}]});
 const cf=wb.addWorksheet('Cash Flow');base(cf);widths(cf,[24,...months.map(()=>15),18]);title(cf,'CASH FLOW STATEMENT','Operating cash flow derived from recorded revenue, fees, refunds and expenses.',2+months.length);cf.getRow(4).values=['Cash flow item',...months.map((m:any)=>m.month),'Total'];header(cf.getRow(4));[['Cash receipts','revenue'],['Payment fees','fees'],['Refunds','refunds'],['Operating expenses','expenses'],['Net operating cash flow','net']].forEach((x:any,i:number)=>{const rr=5+i;cf.getCell(rr,1).value=x[0];months.forEach((m:any,j:number)=>{const sign=i===0||i===4?1:-1;cf.getCell(rr,2+j).value=sign*m[x[1]];cf.getCell(rr,2+j).numFmt=euro});cf.getCell(rr,2+months.length).value={formula:`SUM(B${rr}:${cf.getCell(rr,1+months.length).address})`};cf.getCell(rr,2+months.length).numFmt=euro});
 const subs=wb.addWorksheet('Subscriptions');base(subs);widths(subs,[24,22,18,18,18,22]);title(subs,'SUBSCRIPTION INTELLIGENCE','Member status and plan mix. Personally identifying data is intentionally excluded from this executive export.',6);const planMap=new Map<string,{active:number,cancelled:number,total:number}>();for(const m of input.members){const p=String(m.plan||'Unknown');const x=planMap.get(p)||{active:0,cancelled:0,total:0};x.total++;if(['active','trialing'].includes(String(m.subscriptionStatus).toLowerCase()))x.active++;if(m.cancelAtPeriodEnd||String(m.subscriptionStatus).toLowerCase()==='cancelled')x.cancelled++;planMap.set(p,x)}addTable(subs,'SubscriptionPlans','A4',['Plan','Active','Cancelled','Total Records','Active Rate','Cancellation Rate'],[...planMap.entries()].map(([p,x])=>[p,x.active,x.cancelled,x.total,x.total?x.active/x.total:0,x.total?x.cancelled/x.total:0]));subs.getColumn(5).numFmt=pct;subs.getColumn(6).numFmt=pct;
 const raw=wb.addWorksheet('Event Data — Pivot Ready',{state:'visible'});base(raw);widths(raw,[20,20,24,26,24,24,20,18,18,18,18,20,24,20,20]);title(raw,'EVENT DATA — PIVOT READY','Filterable source table for deeper Excel analysis. No direct personal identifiers are exported.',15);addTable(raw,'AnalyticsEvents','A4',['Date','Event Type','Entity Type','Title','Artist','Album','Product','Country','Region','City','Device','Referrer','Listened Seconds','Session','Anonymous Visitor'],input.events.filter(e=>{const d=asDate(e.createdAt||e.receivedAt);return d>=input.start&&d<=input.end}).map(e=>[asDate(e.createdAt||e.receivedAt),e.eventType,e.entityType,e.title||e.entityId,e.artistName||e.artistId,e.albumTitle,e.productName||e.productId,e.country,e.region,e.city,e.deviceType,e.referrer,e.listenedSeconds,e.sessionId,e.visitorId]));raw.getColumn(1).numFmt='dd mmm yyyy hh:mm';
 const dict=wb.addWorksheet('Report Guide');base(dict);widths(dict,[28,90]);title(dict,'REPORT GUIDE & CONTROL NOTES','How to use this workbook and understand its limitations.',2);const guide=[['Purpose','Executive decision support across revenue, music, artists, merchandise, subscriptions and geography.'],['Filtering','Every detailed dataset is a native Excel Table. Use the filter arrows in the header row to filter by any available field.'],['Pivot analysis','The Event Data — Pivot Ready sheet is structured specifically so a desktop Excel user can insert PivotTables and slicers without cleaning the data first.'],['Charts','Dashboard visual summaries are represented through executive KPI panels and conditional-format heat scales. The browser export engine cannot reliably author genuine Excel PivotCharts or slicers.'],['Financial statements','The income statement and cash flow use recorded transactions. The balance sheet contains highlighted management-input cells because bank balances, inventory value, liabilities and equity are not yet available from the website database.'],['Privacy','Direct customer names and email addresses are excluded from this executive report. Anonymous visitor IDs are random browser identifiers used only to count unique visitors and are not customer identities.'],['Data coverage',`Reporting window: ${input.start.toISOString()} to ${input.end.toISOString()}. Unique visitor counts begin when anonymous visitor tracking is deployed; earlier activity cannot be reconstructed.`]];dict.getRange?.('A4:B10');guide.forEach((x,i)=>{dict.getRow(4+i).values=x;dict.getCell(4+i,1).font={bold:true,color:{argb:NAVY}};dict.getCell(4+i,2).alignment={wrapText:true,vertical:'top'};dict.getRow(4+i).height=40});
 wb.worksheets.forEach((ws:any)=>{ws.eachRow((row:any)=>row.eachCell((cell:any)=>{cell.font={name:'Aptos',size:10,...cell.font};cell.alignment={vertical:'middle',...cell.alignment}}));});
 const buffer=await wb.xlsx.writeBuffer();const blob=new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`Aureon-Executive-Intelligence-${new Date().toISOString().slice(0,10)}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);
}