import type { Locale } from './config';

type PhraseMap = Record<string, string>;

const pt: PhraseMap = {
  'Home':'Início','Artists':'Artistas','Music':'Música','Videos':'Vídeos','Membership':'Assinatura','News':'Notícias','About':'Sobre','Contact':'Contacto','Search':'Pesquisar','Login':'Entrar','My Account':'Minha Conta','Member account':'Conta de membro','Language':'Idioma','Store':'Loja','Merch':'Loja',
  'Watch now':'Ver agora','WATCH NOW':'VER AGORA','Featured Videos':'Vídeos em destaque','Featured videos':'Vídeos em destaque','View all videos':'Ver todos os vídeos','VIEW ALL VIDEOS':'VER TODOS OS VÍDEOS','40-second audio preview':'Prévia de áudio de 40 segundos','40-SECOND AUDIO PREVIEW':'PRÉVIA DE ÁUDIO DE 40 SEGUNDOS',
  'Our Artists':'Os nossos artistas','OUR ARTISTS':'OS NOSSOS ARTISTAS','View Artist':'Ver artista','VIEW ARTIST':'VER ARTISTA','Aureon Artist':'Artista Aureon','AUREON ARTIST':'ARTISTA AUREON','Official Artist':'Artista oficial','Official Album':'Álbum oficial','Official Video':'Vídeo oficial','Official Aureon Video':'Vídeo oficial Aureon','OFFICIAL VIDEO':'VÍDEO OFICIAL','OFFICIAL AUREON VIDEO':'VÍDEO OFICIAL AUREON',
  'Music videos and visual releases':'Vídeos musicais e lançamentos visuais','Aureon Visual Catalogue':'Catálogo visual Aureon','AUREON VISUAL CATALOGUE':'CATÁLOGO VISUAL AUREON','Latest videos':'Vídeos mais recentes','Play on Aureon':'Reproduzir na Aureon','PLAY ON AUREON':'REPRODUZIR NA AUREON','Music Video':'Vídeo musical','MUSIC VIDEO':'VÍDEO MUSICAL',
  'New Releases':'Novos lançamentos','NEW RELEASES':'NOVOS LANÇAMENTOS','Fresh From Aureon':'Novidades da Aureon','FRESH FROM AUREON':'NOVIDADES DA AUREON','View all':'Ver tudo','Play':'Reproduzir','PLAY':'REPRODUZIR','Play Preview':'Ouvir prévia','PLAY PREVIEW':'OUVIR PRÉVIA','Preview coming soon.':'Prévia disponível em breve.','HD AUDIO':'ÁUDIO HD','HD Audio':'Áudio HD',
  'Continue Listening':'Continuar a ouvir','Resume from your exact position.':'Retome exatamente de onde parou.','Sign in to continue listening':'Entre para continuar a ouvir','Recently Played':'Ouvido recentemente','Trending Now':'Em alta agora','Songs building momentum across Aureon.':'Músicas a ganhar destaque na Aureon.','Recommended Artists':'Artistas recomendados','Recommended Albums':'Álbuns recomendados','Recommended Playlists':'Playlists recomendadas','You May Like':'Pode gostar','You May Also Like':'Também pode gostar','Fans Also Like':'Os fãs também gostam','More Albums Like This':'Mais álbuns semelhantes','Create a free account':'Criar conta gratuita','CREATE A FREE ACCOUNT':'CRIAR CONTA GRATUITA',
  'Track List':'Lista de faixas','TRACK LIST':'LISTA DE FAIXAS','Songs in this album':'Músicas deste álbum','Back to music':'Voltar à música','Digital download':'Download digital','Buy full song':'Comprar música completa','Secure payment':'Pagamento seguro','Instant ownership':'Propriedade imediata','40s Preview':'Prévia de 40s','Your preview has finished':'A sua prévia terminou','Keep the music going':'Continue a ouvir','Explore Premium':'Explorar Premium','Create Free Account':'Criar conta gratuita','Purchase This Song':'Comprar esta música','Replay the 40-second preview':'Repetir a prévia de 40 segundos',
  'Videos':'Vídeos','Latest Videos':'Vídeos mais recentes','Back to videos':'Voltar aos vídeos','Back to video albums':'Voltar aos álbuns de vídeo','Video List':'Lista de vídeos','Videos in this album':'Vídeos deste álbum','Video coming soon.':'Vídeo disponível em breve.','Audio preview finished':'Prévia de áudio terminada','Unlock full audio':'Desbloquear áudio completo',
  'News from Aureon':'Notícias da Aureon','NEWS FROM AUREON':'NOTÍCIAS DA AUREON','View all news':'Ver todas as notícias','VIEW ALL NEWS':'VER TODAS AS NOTÍCIAS','Featured News':'Notícia em destaque','FEATURED NEWS':'NOTÍCIA EM DESTAQUE','Read story':'Ler artigo','Read more':'Ler mais',
  'Discover':'Descobrir','Library':'Biblioteca','Search song, artist or genre':'Pesquisar música, artista ou género','All artists':'Todos os artistas','All genres':'Todos os géneros','Queue':'Fila','QUEUE':'FILA','Download':'Download','DOWNLOAD':'DOWNLOAD','Choose playlist':'Escolher playlist','Add':'Adicionar','Follow':'Seguir','Following':'A seguir','Favourite':'Favorito','Favourites':'Favoritos',
  'Premium':'Premium','Join Premium':'Aderir ao Premium','Become an Aureon Premium Member':'Torne-se membro Aureon Premium','Unlimited listening':'Audição ilimitada','Complete Aureon catalogue':'Catálogo Aureon completo','Exclusive early releases':'Lançamentos antecipados exclusivos','High-quality audio':'Áudio de alta qualidade','Global access':'Acesso global','Secure payments':'Pagamentos seguros','Privacy first':'Privacidade em primeiro lugar','Official Aureon platform':'Plataforma oficial Aureon',
  'Contact us':'Contacte-nos','Get in touch':'Entre em contacto','Send message':'Enviar mensagem','Name':'Nome','Email':'E-mail','Message':'Mensagem','About Aureon':'Sobre a Aureon','Learn more':'Saber mais','Back':'Voltar','Loading…':'A carregar…','No results found':'Nenhum resultado encontrado','Sign in':'Entrar','Sign out':'Sair','Create account':'Criar conta','Account':'Conta','Checkout':'Finalizar compra','Cart':'Carrinho'
};

const es: PhraseMap = {
  'Home':'Inicio','Artists':'Artistas','Music':'Música','Videos':'Vídeos','Membership':'Membresía','News':'Noticias','About':'Acerca de','Contact':'Contacto','Search':'Buscar','Login':'Entrar','My Account':'Mi cuenta','Member account':'Cuenta de miembro','Language':'Idioma','Store':'Tienda','Merch':'Tienda',
  'Watch now':'Ver ahora','WATCH NOW':'VER AHORA','Featured Videos':'Vídeos destacados','Featured videos':'Vídeos destacados','View all videos':'Ver todos los vídeos','VIEW ALL VIDEOS':'VER TODOS LOS VÍDEOS','40-second audio preview':'Vista previa de audio de 40 segundos','40-SECOND AUDIO PREVIEW':'VISTA PREVIA DE AUDIO DE 40 SEGUNDOS',
  'Our Artists':'Nuestros artistas','OUR ARTISTS':'NUESTROS ARTISTAS','View Artist':'Ver artista','VIEW ARTIST':'VER ARTISTA','Aureon Artist':'Artista Aureon','AUREON ARTIST':'ARTISTA AUREON','Official Artist':'Artista oficial','Official Album':'Álbum oficial','Official Video':'Vídeo oficial','Official Aureon Video':'Vídeo oficial Aureon','OFFICIAL VIDEO':'VÍDEO OFICIAL','OFFICIAL AUREON VIDEO':'VÍDEO OFICIAL AUREON',
  'Music videos and visual releases':'Vídeos musicales y lanzamientos visuales','Aureon Visual Catalogue':'Catálogo visual Aureon','AUREON VISUAL CATALOGUE':'CATÁLOGO VISUAL AUREON','Latest videos':'Últimos vídeos','Play on Aureon':'Reproducir en Aureon','PLAY ON AUREON':'REPRODUCIR EN AUREON','Music Video':'Vídeo musical','MUSIC VIDEO':'VÍDEO MUSICAL',
  'New Releases':'Nuevos lanzamientos','NEW RELEASES':'NUEVOS LANZAMIENTOS','Fresh From Aureon':'Novedades de Aureon','FRESH FROM AUREON':'NOVEDADES DE AUREON','View all':'Ver todo','Play':'Reproducir','PLAY':'REPRODUCIR','Play Preview':'Escuchar vista previa','PLAY PREVIEW':'ESCUCHAR VISTA PREVIA','Preview coming soon.':'Vista previa próximamente.','HD AUDIO':'AUDIO HD','HD Audio':'Audio HD',
  'Continue Listening':'Seguir escuchando','Resume from your exact position.':'Continúa exactamente donde lo dejaste.','Sign in to continue listening':'Inicia sesión para seguir escuchando','Recently Played':'Reproducido recientemente','Trending Now':'Tendencias ahora','Songs building momentum across Aureon.':'Canciones ganando impulso en Aureon.','Recommended Artists':'Artistas recomendados','Recommended Albums':'Álbumes recomendados','Recommended Playlists':'Playlists recomendadas','You May Like':'Te puede gustar','You May Also Like':'También te puede gustar','Fans Also Like':'A los fans también les gusta','More Albums Like This':'Más álbumes como este','Create a free account':'Crear cuenta gratuita','CREATE A FREE ACCOUNT':'CREAR CUENTA GRATUITA',
  'Track List':'Lista de canciones','TRACK LIST':'LISTA DE CANCIONES','Songs in this album':'Canciones de este álbum','Back to music':'Volver a música','Digital download':'Descarga digital','Buy full song':'Comprar canción completa','Secure payment':'Pago seguro','Instant ownership':'Propiedad inmediata','40s Preview':'Vista previa 40s','Your preview has finished':'Tu vista previa ha terminado','Keep the music going':'Sigue con la música','Explore Premium':'Explorar Premium','Create Free Account':'Crear cuenta gratuita','Purchase This Song':'Comprar esta canción','Replay the 40-second preview':'Repetir vista previa de 40 segundos',
  'Latest Videos':'Últimos vídeos','Back to videos':'Volver a vídeos','Back to video albums':'Volver a álbumes de vídeo','Video List':'Lista de vídeos','Videos in this album':'Vídeos de este álbum','Video coming soon.':'Vídeo próximamente.','Audio preview finished':'Vista previa de audio finalizada','Unlock full audio':'Desbloquear audio completo',
  'News from Aureon':'Noticias de Aureon','NEWS FROM AUREON':'NOTICIAS DE AUREON','View all news':'Ver todas las noticias','VIEW ALL NEWS':'VER TODAS LAS NOTICIAS','Featured News':'Noticia destacada','FEATURED NEWS':'NOTICIA DESTACADA','Read story':'Leer artículo','Read more':'Leer más',
  'Discover':'Descubrir','Library':'Biblioteca','Search song, artist or genre':'Buscar canción, artista o género','All artists':'Todos los artistas','All genres':'Todos los géneros','Queue':'Cola','QUEUE':'COLA','Download':'Descargar','DOWNLOAD':'DESCARGAR','Choose playlist':'Elegir playlist','Add':'Añadir','Follow':'Seguir','Following':'Siguiendo','Favourite':'Favorito','Favourites':'Favoritos',
  'Premium':'Premium','Join Premium':'Unirse a Premium','Become an Aureon Premium Member':'Hazte miembro Aureon Premium','Unlimited listening':'Escucha ilimitada','Complete Aureon catalogue':'Catálogo Aureon completo','Exclusive early releases':'Lanzamientos anticipados exclusivos','High-quality audio':'Audio de alta calidad','Global access':'Acceso global','Secure payments':'Pagos seguros','Privacy first':'Privacidad primero','Official Aureon platform':'Plataforma oficial Aureon',
  'Contact us':'Contáctanos','Get in touch':'Ponte en contacto','Send message':'Enviar mensaje','Name':'Nombre','Email':'Correo electrónico','Message':'Mensaje','About Aureon':'Acerca de Aureon','Learn more':'Saber más','Back':'Volver','Loading…':'Cargando…','No results found':'No se encontraron resultados','Sign in':'Iniciar sesión','Sign out':'Cerrar sesión','Create account':'Crear cuenta','Account':'Cuenta','Checkout':'Pagar','Cart':'Carrito'
};

const fr: PhraseMap = {
  'Home':'Accueil','Artists':'Artistes','Music':'Musique','Videos':'Vidéos','Membership':'Abonnement','News':'Actualités','About':'À propos','Contact':'Contact','Search':'Rechercher','Login':'Connexion','My Account':'Mon compte','Member account':'Compte membre','Language':'Langue','Store':'Boutique','Merch':'Boutique',
  'Watch now':'Regarder maintenant','WATCH NOW':'REGARDER MAINTENANT','Featured Videos':'Vidéos à la une','Featured videos':'Vidéos à la une','View all videos':'Voir toutes les vidéos','VIEW ALL VIDEOS':'VOIR TOUTES LES VIDÉOS','40-second audio preview':'Extrait audio de 40 secondes','40-SECOND AUDIO PREVIEW':'EXTRAIT AUDIO DE 40 SECONDES',
  'Our Artists':'Nos artistes','OUR ARTISTS':'NOS ARTISTES','View Artist':'Voir l’artiste','VIEW ARTIST':'VOIR L’ARTISTE','Aureon Artist':'Artiste Aureon','AUREON ARTIST':'ARTISTE AUREON','Official Artist':'Artiste officiel','Official Album':'Album officiel','Official Video':'Vidéo officielle','Official Aureon Video':'Vidéo officielle Aureon','OFFICIAL VIDEO':'VIDÉO OFFICIELLE','OFFICIAL AUREON VIDEO':'VIDÉO OFFICIELLE AUREON',
  'Music videos and visual releases':'Clips musicaux et sorties visuelles','Aureon Visual Catalogue':'Catalogue visuel Aureon','AUREON VISUAL CATALOGUE':'CATALOGUE VISUEL AUREON','Latest videos':'Dernières vidéos','Play on Aureon':'Lire sur Aureon','PLAY ON AUREON':'LIRE SUR AUREON','Music Video':'Clip musical','MUSIC VIDEO':'CLIP MUSICAL',
  'New Releases':'Nouvelles sorties','NEW RELEASES':'NOUVELLES SORTIES','Fresh From Aureon':'Nouveautés Aureon','FRESH FROM AUREON':'NOUVEAUTÉS AUREON','View all':'Voir tout','Play':'Lire','PLAY':'LIRE','Play Preview':'Écouter l’extrait','PLAY PREVIEW':'ÉCOUTER L’EXTRAIT','Preview coming soon.':'Extrait bientôt disponible.','HD AUDIO':'AUDIO HD','HD Audio':'Audio HD',
  'Continue Listening':'Continuer l’écoute','Resume from your exact position.':'Reprenez exactement où vous vous êtes arrêté.','Sign in to continue listening':'Connectez-vous pour continuer l’écoute','Recently Played':'Écouté récemment','Trending Now':'Tendances actuelles','Songs building momentum across Aureon.':'Titres qui gagnent en popularité sur Aureon.','Recommended Artists':'Artistes recommandés','Recommended Albums':'Albums recommandés','Recommended Playlists':'Playlists recommandées','You May Like':'Vous pourriez aimer','You May Also Like':'Vous aimerez peut-être aussi','Fans Also Like':'Les fans aiment aussi','More Albums Like This':'Plus d’albums similaires','Create a free account':'Créer un compte gratuit','CREATE A FREE ACCOUNT':'CRÉER UN COMPTE GRATUIT',
  'Track List':'Liste des titres','TRACK LIST':'LISTE DES TITRES','Songs in this album':'Titres de cet album','Back to music':'Retour à la musique','Digital download':'Téléchargement numérique','Buy full song':'Acheter le titre complet','Secure payment':'Paiement sécurisé','Instant ownership':'Propriété immédiate','40s Preview':'Extrait 40s','Your preview has finished':'Votre extrait est terminé','Keep the music going':'Continuez la musique','Explore Premium':'Découvrir Premium','Create Free Account':'Créer un compte gratuit','Purchase This Song':'Acheter ce titre','Replay the 40-second preview':'Réécouter l’extrait de 40 secondes',
  'Latest Videos':'Dernières vidéos','Back to videos':'Retour aux vidéos','Back to video albums':'Retour aux albums vidéo','Video List':'Liste des vidéos','Videos in this album':'Vidéos de cet album','Video coming soon.':'Vidéo bientôt disponible.','Audio preview finished':'Extrait audio terminé','Unlock full audio':'Débloquer l’audio complet',
  'News from Aureon':'Actualités Aureon','NEWS FROM AUREON':'ACTUALITÉS AUREON','View all news':'Voir toutes les actualités','VIEW ALL NEWS':'VOIR TOUTES LES ACTUALITÉS','Featured News':'Actualité à la une','FEATURED NEWS':'ACTUALITÉ À LA UNE','Read story':'Lire l’article','Read more':'Lire la suite',
  'Discover':'Découvrir','Library':'Bibliothèque','Search song, artist or genre':'Rechercher un titre, un artiste ou un genre','All artists':'Tous les artistes','All genres':'Tous les genres','Queue':'File d’attente','QUEUE':'FILE D’ATTENTE','Download':'Télécharger','DOWNLOAD':'TÉLÉCHARGER','Choose playlist':'Choisir une playlist','Add':'Ajouter','Follow':'Suivre','Following':'Suivi','Favourite':'Favori','Favourites':'Favoris',
  'Premium':'Premium','Join Premium':'Rejoindre Premium','Become an Aureon Premium Member':'Devenez membre Aureon Premium','Unlimited listening':'Écoute illimitée','Complete Aureon catalogue':'Catalogue Aureon complet','Exclusive early releases':'Sorties anticipées exclusives','High-quality audio':'Audio haute qualité','Global access':'Accès mondial','Secure payments':'Paiements sécurisés','Privacy first':'Confidentialité prioritaire','Official Aureon platform':'Plateforme officielle Aureon',
  'Contact us':'Nous contacter','Get in touch':'Contactez-nous','Send message':'Envoyer le message','Name':'Nom','Email':'E-mail','Message':'Message','About Aureon':'À propos d’Aureon','Learn more':'En savoir plus','Back':'Retour','Loading…':'Chargement…','No results found':'Aucun résultat trouvé','Sign in':'Connexion','Sign out':'Déconnexion','Create account':'Créer un compte','Account':'Compte','Checkout':'Paiement','Cart':'Panier'
};

const de: PhraseMap = {
  'Home':'Startseite','Artists':'Künstler','Music':'Musik','Videos':'Videos','Membership':'Mitgliedschaft','News':'Neuigkeiten','About':'Über uns','Contact':'Kontakt','Search':'Suche','Login':'Anmelden','My Account':'Mein Konto','Member account':'Mitgliedskonto','Language':'Sprache','Store':'Shop','Merch':'Shop',
  'Watch now':'Jetzt ansehen','WATCH NOW':'JETZT ANSEHEN','Featured Videos':'Empfohlene Videos','Featured videos':'Empfohlene Videos','View all videos':'Alle Videos ansehen','VIEW ALL VIDEOS':'ALLE VIDEOS ANSEHEN','40-second audio preview':'40-Sekunden-Audiovorschau','40-SECOND AUDIO PREVIEW':'40-SEKUNDEN-AUDIOVORSCHAU',
  'Our Artists':'Unsere Künstler','OUR ARTISTS':'UNSERE KÜNSTLER','View Artist':'Künstler ansehen','VIEW ARTIST':'KÜNSTLER ANSEHEN','Aureon Artist':'Aureon-Künstler','AUREON ARTIST':'AUREON-KÜNSTLER','Official Artist':'Offizieller Künstler','Official Album':'Offizielles Album','Official Video':'Offizielles Video','Official Aureon Video':'Offizielles Aureon-Video','OFFICIAL VIDEO':'OFFIZIELLES VIDEO','OFFICIAL AUREON VIDEO':'OFFIZIELLES AUREON-VIDEO',
  'Music videos and visual releases':'Musikvideos und visuelle Veröffentlichungen','Aureon Visual Catalogue':'Aureon Videokatalog','AUREON VISUAL CATALOGUE':'AUREON VIDEOKATALOG','Latest videos':'Neueste Videos','Play on Aureon':'Auf Aureon abspielen','PLAY ON AUREON':'AUF AUREON ABSPIELEN','Music Video':'Musikvideo','MUSIC VIDEO':'MUSIKVIDEO',
  'New Releases':'Neuerscheinungen','NEW RELEASES':'NEUERSCHEINUNGEN','Fresh From Aureon':'Neu bei Aureon','FRESH FROM AUREON':'NEU BEI AUREON','View all':'Alle ansehen','Play':'Abspielen','PLAY':'ABSPIELEN','Play Preview':'Vorschau abspielen','PLAY PREVIEW':'VORSCHAU ABSPIELEN','Preview coming soon.':'Vorschau folgt in Kürze.','HD AUDIO':'HD-AUDIO','HD Audio':'HD-Audio',
  'Continue Listening':'Weiterhören','Resume from your exact position.':'Genau an deiner letzten Stelle fortsetzen.','Sign in to continue listening':'Zum Weiterhören anmelden','Recently Played':'Zuletzt gespielt','Trending Now':'Gerade angesagt','Songs building momentum across Aureon.':'Songs mit wachsender Dynamik auf Aureon.','Recommended Artists':'Empfohlene Künstler','Recommended Albums':'Empfohlene Alben','Recommended Playlists':'Empfohlene Playlists','You May Like':'Das könnte dir gefallen','You May Also Like':'Das könnte dir auch gefallen','Fans Also Like':'Fans mögen auch','More Albums Like This':'Weitere ähnliche Alben','Create a free account':'Kostenloses Konto erstellen','CREATE A FREE ACCOUNT':'KOSTENLOSES KONTO ERSTELLEN',
  'Track List':'Titelliste','TRACK LIST':'TITELLISTE','Songs in this album':'Songs in diesem Album','Back to music':'Zurück zur Musik','Digital download':'Digitaler Download','Buy full song':'Kompletten Song kaufen','Secure payment':'Sichere Zahlung','Instant ownership':'Sofortiger Besitz','40s Preview':'40s Vorschau','Your preview has finished':'Deine Vorschau ist beendet','Keep the music going':'Musik weiterlaufen lassen','Explore Premium':'Premium entdecken','Create Free Account':'Kostenloses Konto erstellen','Purchase This Song':'Diesen Song kaufen','Replay the 40-second preview':'40-Sekunden-Vorschau wiederholen',
  'Latest Videos':'Neueste Videos','Back to videos':'Zurück zu Videos','Back to video albums':'Zurück zu Videoalben','Video List':'Videoliste','Videos in this album':'Videos in diesem Album','Video coming soon.':'Video folgt in Kürze.','Audio preview finished':'Audiovorschau beendet','Unlock full audio':'Vollständiges Audio freischalten',
  'News from Aureon':'Neuigkeiten von Aureon','NEWS FROM AUREON':'NEUIGKEITEN VON AUREON','View all news':'Alle Neuigkeiten ansehen','VIEW ALL NEWS':'ALLE NEUIGKEITEN ANSEHEN','Featured News':'Top-Neuigkeit','FEATURED NEWS':'TOP-NEUIGKEIT','Read story':'Artikel lesen','Read more':'Mehr lesen',
  'Discover':'Entdecken','Library':'Bibliothek','Search song, artist or genre':'Song, Künstler oder Genre suchen','All artists':'Alle Künstler','All genres':'Alle Genres','Queue':'Warteschlange','QUEUE':'WARTESCHLANGE','Download':'Herunterladen','DOWNLOAD':'HERUNTERLADEN','Choose playlist':'Playlist auswählen','Add':'Hinzufügen','Follow':'Folgen','Following':'Gefolgt','Favourite':'Favorit','Favourites':'Favoriten',
  'Premium':'Premium','Join Premium':'Premium beitreten','Become an Aureon Premium Member':'Aureon Premium-Mitglied werden','Unlimited listening':'Unbegrenztes Hören','Complete Aureon catalogue':'Vollständiger Aureon-Katalog','Exclusive early releases':'Exklusive Vorabveröffentlichungen','High-quality audio':'Hochwertiges Audio','Global access':'Weltweiter Zugriff','Secure payments':'Sichere Zahlungen','Privacy first':'Datenschutz zuerst','Official Aureon platform':'Offizielle Aureon-Plattform',
  'Contact us':'Kontaktieren Sie uns','Get in touch':'Kontakt aufnehmen','Send message':'Nachricht senden','Name':'Name','Email':'E-Mail','Message':'Nachricht','About Aureon':'Über Aureon','Learn more':'Mehr erfahren','Back':'Zurück','Loading…':'Wird geladen…','No results found':'Keine Ergebnisse gefunden','Sign in':'Anmelden','Sign out':'Abmelden','Create account':'Konto erstellen','Account':'Konto','Checkout':'Zur Kasse','Cart':'Warenkorb'
};

export const interfaceTranslations: Record<Locale, PhraseMap> = { en: {}, pt, es, fr, de };
