import type { Locale } from './config';

type PhraseMap = Record<string,string>;

const pt: PhraseMap = {
  'Stripe encrypted checkout':'Pagamento encriptado pela Stripe','Listen wherever available':'Ouça onde estiver disponível','Aureon Legal Centre':'Centro Jurídico Aureon',
  'Subscriptions renew monthly until cancelled. Creator licence rights require an active Creator subscription. All public terms are available in the':'As assinaturas renovam mensalmente até serem canceladas. Os direitos de licença de criador exigem uma assinatura Criador ativa. Todos os termos públicos estão disponíveis no',
  'Active — cancels at period end':'Ativa — cancela no fim do período','Confirming your Aureon membership…':'A confirmar a sua assinatura Aureon…','Your Aureon membership plan has been updated.':'O seu plano de assinatura Aureon foi atualizado.','Account created. We sent a verification link to your email address.':'Conta criada. Enviámos um link de verificação para o seu endereço de e-mail.','Signed in. Please verify your email before subscribing.':'Sessão iniciada. Verifique o seu e-mail antes de subscrever.','The email or password is incorrect.':'O e-mail ou a palavra-passe estão incorretos.','Enter your email address first, then select Reset password.':'Introduza primeiro o seu endereço de e-mail e depois selecione Redefinir palavra-passe.','Password reset email sent. Check your inbox and spam folder.':'E-mail de redefinição de palavra-passe enviado. Verifique a caixa de entrada e o spam.','Verification email sent. Check your inbox and spam folder.':'E-mail de verificação enviado. Verifique a caixa de entrada e o spam.','Email address verified.':'Endereço de e-mail verificado.','Email is not verified yet. Open the link in your email, then try again.':'O e-mail ainda não está verificado. Abra o link no seu e-mail e tente novamente.','Verify your email address before starting a paid membership.':'Verifique o seu endereço de e-mail antes de iniciar uma assinatura paga.','Profile details updated.':'Dados do perfil atualizados.','Unable to update profile.':'Não foi possível atualizar o perfil.',
  'Commercial use':'Utilização comercial','Licence certificates':'Certificados de licença','Creator downloads':'Downloads de criador','Account trust and security':'Confiança e segurança da conta',
  'Full name':'Nome completo','Your full name':'O seu nome completo','Email address':'Endereço de e-mail','Create account':'Criar conta','Account':'Conta','Verified':'Verificado','Not verified':'Não verificado',
  'Public':'Público','Private':'Privado','Untitled playlist':'Playlist sem título','Untitled track':'Música sem título','Public collection':'Coleção pública','Private collection':'Coleção privada',
  'Loading your referral programme…':'A carregar o seu programa de referências…','Unable to load referrals.':'Não foi possível carregar as referências.','Copied':'Copiado','Premium member':'Membro Premium','Account created':'Conta criada','No badges unlocked yet.':'Ainda não existem distintivos desbloqueados.','Your first paid referral unlocks the Aureon Ambassador vault.':'A sua primeira referência paga desbloqueia o espaço Embaixador Aureon.','Rewards are granted only after verified account and Stripe subscription events. Self-referrals and duplicate claims are blocked.':'As recompensas só são atribuídas após eventos verificados de conta e assinatura Stripe. Auto-referências e pedidos duplicados são bloqueados.',
  'Resume your journey':'Retome a sua jornada','Open library':'Abrir biblioteca','Your listening history':'O seu histórico de audição','Played':'Ouvido','Replay':'Ouvir novamente','Recently':'Recentemente','Just now':'Agora mesmo',
  'Five distinct songs per billing month':'Cinco músicas distintas por mês de faturação','your next billing date':'a sua próxima data de faturação','No listening history yet. Play a track to begin.':'Ainda não existe histórico de audição. Reproduza uma música para começar.','No member downloads yet.':'Ainda não existem downloads de membro.'
};

const es: PhraseMap = {
  'Stripe encrypted checkout':'Pago cifrado por Stripe','Listen wherever available':'Escucha donde esté disponible','Aureon Legal Centre':'Centro Legal Aureon','Subscriptions renew monthly until cancelled. Creator licence rights require an active Creator subscription. All public terms are available in the':'Las suscripciones se renuevan mensualmente hasta su cancelación. Los derechos de licencia de Creador requieren una suscripción Creador activa. Todos los términos públicos están disponibles en el','Active — cancels at period end':'Activa — se cancela al final del período','Confirming your Aureon membership…':'Confirmando tu membresía Aureon…','Your Aureon membership plan has been updated.':'Tu plan de membresía Aureon se ha actualizado.','Account created. We sent a verification link to your email address.':'Cuenta creada. Enviamos un enlace de verificación a tu correo electrónico.','Signed in. Please verify your email before subscribing.':'Sesión iniciada. Verifica tu correo antes de suscribirte.','The email or password is incorrect.':'El correo o la contraseña son incorrectos.','Enter your email address first, then select Reset password.':'Introduce primero tu correo y después selecciona Restablecer contraseña.','Password reset email sent. Check your inbox and spam folder.':'Correo de restablecimiento enviado. Revisa tu bandeja de entrada y spam.','Verification email sent. Check your inbox and spam folder.':'Correo de verificación enviado. Revisa tu bandeja de entrada y spam.','Email address verified.':'Correo electrónico verificado.','Email is not verified yet. Open the link in your email, then try again.':'El correo aún no está verificado. Abre el enlace de tu correo e inténtalo de nuevo.','Verify your email address before starting a paid membership.':'Verifica tu correo antes de iniciar una membresía de pago.','Profile details updated.':'Datos del perfil actualizados.','Unable to update profile.':'No se pudo actualizar el perfil.','Full name':'Nombre completo','Your full name':'Tu nombre completo','Email address':'Correo electrónico','Public':'Público','Private':'Privado','Untitled playlist':'Playlist sin título','Untitled track':'Canción sin título','Loading your referral programme…':'Cargando tu programa de referidos…','Unable to load referrals.':'No se pudieron cargar los referidos.','Premium member':'Miembro Premium','Resume your journey':'Retoma tu viaje','Open library':'Abrir biblioteca','Your listening history':'Tu historial de escucha','Played':'Reproducido','Replay':'Reproducir de nuevo','Recently':'Recientemente','Just now':'Ahora mismo','your next billing date':'tu próxima fecha de facturación'
};

const fr: PhraseMap = {
  'Stripe encrypted checkout':'Paiement chiffré par Stripe','Listen wherever available':'Écoutez partout où le service est disponible','Aureon Legal Centre':'Centre juridique Aureon','Subscriptions renew monthly until cancelled. Creator licence rights require an active Creator subscription. All public terms are available in the':'Les abonnements sont renouvelés chaque mois jusqu’à résiliation. Les droits de licence Créateur nécessitent un abonnement Créateur actif. Toutes les conditions publiques sont disponibles dans le','Active — cancels at period end':'Actif — résiliation en fin de période','Confirming your Aureon membership…':'Confirmation de votre abonnement Aureon…','Your Aureon membership plan has been updated.':'Votre offre Aureon a été mise à jour.','Account created. We sent a verification link to your email address.':'Compte créé. Nous avons envoyé un lien de vérification à votre adresse e-mail.','Signed in. Please verify your email before subscribing.':'Connecté. Veuillez vérifier votre e-mail avant de vous abonner.','The email or password is incorrect.':'L’e-mail ou le mot de passe est incorrect.','Enter your email address first, then select Reset password.':'Saisissez d’abord votre adresse e-mail, puis sélectionnez Réinitialiser le mot de passe.','Password reset email sent. Check your inbox and spam folder.':'E-mail de réinitialisation envoyé. Vérifiez votre boîte de réception et les indésirables.','Verification email sent. Check your inbox and spam folder.':'E-mail de vérification envoyé. Vérifiez votre boîte de réception et les indésirables.','Email address verified.':'Adresse e-mail vérifiée.','Email is not verified yet. Open the link in your email, then try again.':'L’e-mail n’est pas encore vérifié. Ouvrez le lien reçu puis réessayez.','Verify your email address before starting a paid membership.':'Vérifiez votre adresse e-mail avant de commencer un abonnement payant.','Profile details updated.':'Informations du profil mises à jour.','Unable to update profile.':'Impossible de mettre à jour le profil.','Full name':'Nom complet','Your full name':'Votre nom complet','Email address':'Adresse e-mail','Public':'Public','Private':'Privé','Untitled playlist':'Playlist sans titre','Untitled track':'Titre sans nom','Loading your referral programme…':'Chargement de votre programme de parrainage…','Unable to load referrals.':'Impossible de charger les parrainages.','Premium member':'Membre Premium','Resume your journey':'Reprenez votre parcours','Open library':'Ouvrir la bibliothèque','Your listening history':'Votre historique d’écoute','Played':'Écouté','Replay':'Réécouter','Recently':'Récemment','Just now':'À l’instant','your next billing date':'votre prochaine date de facturation'
};

const de: PhraseMap = {
  'Stripe encrypted checkout':'Stripe-verschlüsselter Checkout','Listen wherever available':'Überall hören, wo verfügbar','Aureon Legal Centre':'Aureon Rechtszentrum','Subscriptions renew monthly until cancelled. Creator licence rights require an active Creator subscription. All public terms are available in the':'Abonnements verlängern sich monatlich bis zur Kündigung. Creator-Lizenzrechte erfordern ein aktives Creator-Abonnement. Alle öffentlichen Bedingungen findest du im','Active — cancels at period end':'Aktiv — endet zum Periodenende','Confirming your Aureon membership…':'Deine Aureon-Mitgliedschaft wird bestätigt…','Your Aureon membership plan has been updated.':'Dein Aureon-Mitgliedschaftstarif wurde aktualisiert.','Account created. We sent a verification link to your email address.':'Konto erstellt. Wir haben einen Bestätigungslink an deine E-Mail-Adresse gesendet.','Signed in. Please verify your email before subscribing.':'Angemeldet. Bitte bestätige deine E-Mail, bevor du abonnierst.','The email or password is incorrect.':'E-Mail oder Passwort ist falsch.','Enter your email address first, then select Reset password.':'Gib zuerst deine E-Mail-Adresse ein und wähle dann Passwort zurücksetzen.','Password reset email sent. Check your inbox and spam folder.':'E-Mail zum Zurücksetzen des Passworts gesendet. Prüfe Posteingang und Spam.','Verification email sent. Check your inbox and spam folder.':'Bestätigungs-E-Mail gesendet. Prüfe Posteingang und Spam.','Email address verified.':'E-Mail-Adresse bestätigt.','Email is not verified yet. Open the link in your email, then try again.':'Die E-Mail ist noch nicht bestätigt. Öffne den Link in deiner E-Mail und versuche es erneut.','Verify your email address before starting a paid membership.':'Bestätige deine E-Mail-Adresse, bevor du eine kostenpflichtige Mitgliedschaft startest.','Profile details updated.':'Profildaten aktualisiert.','Unable to update profile.':'Profil konnte nicht aktualisiert werden.','Full name':'Vollständiger Name','Your full name':'Dein vollständiger Name','Email address':'E-Mail-Adresse','Public':'Öffentlich','Private':'Privat','Untitled playlist':'Unbenannte Playlist','Untitled track':'Unbenannter Titel','Loading your referral programme…':'Dein Empfehlungsprogramm wird geladen…','Unable to load referrals.':'Empfehlungen konnten nicht geladen werden.','Premium member':'Premium-Mitglied','Resume your journey':'Setze deine Reise fort','Open library':'Bibliothek öffnen','Your listening history':'Dein Hörverlauf','Played':'Gespielt','Replay':'Erneut abspielen','Recently':'Kürzlich','Just now':'Gerade eben','your next billing date':'dein nächstes Abrechnungsdatum'
};

export const memberAreaExtraTranslations: Record<Locale,PhraseMap> = { en:{}, pt, es, fr, de };
