'use client';

import { useEffect, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, onSnapshot, serverTimestamp, updateDoc } from 'firebase/firestore';
import { firestore } from '@/lib/firebase-client';
import { AdminShell } from './AdminShell';

const blank={title:'',slug:'',kicker:'',description:'',status:'draft',details:'{}'};
export function SitePageManager(){
 const [items,setItems]=useState<any[]>([]); const [form,setForm]=useState(blank); const [editing,setEditing]=useState<string|null>(null); const [message,setMessage]=useState('');
 useEffect(()=>onSnapshot(collection(firestore,'sitePages'),s=>setItems(s.docs.map(d=>({id:d.id,...d.data()})))),[]);
 function edit(item:any){setEditing(item.id);setForm({title:item.title||'',slug:item.slug||'',kicker:item.kicker||'',description:item.description||'',status:item.status||'draft',details:JSON.stringify(item.details||{},null,2)});}
 async function save(e:React.FormEvent){e.preventDefault();try{const details=JSON.parse(form.details||'{}');const payload={title:form.title.trim(),slug:form.slug.trim(),kicker:form.kicker.trim(),description:form.description.trim(),status:form.status,details,updatedAt:serverTimestamp()};if(editing)await updateDoc(doc(firestore,'sitePages',editing),payload);else await addDoc(collection(firestore,'sitePages'),{...payload,createdAt:serverTimestamp()});setForm(blank);setEditing(null);setMessage('Page settings saved.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to save page settings.');}}
 return <AdminShell><div className="admin-page-heading"><p className="admin-kicker">Aureon Control Center</p><h1>Pages</h1><p>Edit homepage, About and Contact content without changing code.</p></div>{message&&<div className="admin-cms-message">{message}</div>}<section className="admin-cms-grid"><form className="admin-cms-form" onSubmit={save}><h2>{editing?'Edit page':'Create page settings'}</h2><label>Page title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Page slug<input placeholder="home, about or contact" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Kicker<input value={form.kicker} onChange={e=>setForm({...form,kicker:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Advanced page fields (JSON)<textarea rows={12} value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></label><label>Visibility<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft / hidden</option><option value="published">Published / visible</option></select></label><div className="admin-cms-actions"><button className="admin-primary-action" type="submit">Save page</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}</div></form><div className="admin-cms-list"><table><thead><tr><th>Page</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.title}</strong><br/><small>{item.slug}</small></td><td>{item.status}</td><td><div className="admin-row-actions"><button onClick={()=>edit(item)}>Edit</button><button onClick={()=>deleteDoc(doc(firestore,'sitePages',item.id))}>Delete</button></div></td></tr>)}</tbody></table></div></section></AdminShell>;
}
